### ISSUE TITLE
Can't find backups for restore or list

### ISSUE THREAD

**Issue by gruaig** [thelastpickle/cassandra-medusa#12]
Python 3.7.5 (default, Nov 14 2019, 13:29:23)
Docker debian build.

Config file

>[cassandra]
#stop_cmd = /etc/init.d/cassandra stop
#start_cmd = /etc/init.d/cassandra start
#config_file = <path to cassandra.yaml. Defaults to /etc/cassandra/cassandra.yaml>
cql_username = cassandra
cql_password = cassandra
#check_running = <Command ran to verify if Cassandra is running on a node. Defaults to "nodetool version">

>[storage]
storage_provider = local
base_path = /home
bucket_name = shed

>[restore]
;health_check = <Which ports to check when verifying a node restored properly. Options are 'cql' (default), 'thrift', 'all'.>
;query =
;expected_rows =
;expected_result = <Coma separated string representation of values returned by the query. Checks only 1st row returned, and only if specified>

root@uk_staging-cassandra-03:/etc/medusa# medusa backup
[2019-11-19 14:23:52] INFO: Monitoring provider is noop
[2019-11-19 14:23:52] WARNING: is ccm : 0
[2019-11-19 14:23:52] ERROR: This error happened during the backup: Error: Backup 2019111914 already exists
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/medusa/backup.py", line 191, in main
raise IOError('Error: Backup {} already exists'.format(backup_name))
OSError: Error: Backup 2019111914 already exists

Proof the backup exists ^ Which was created a few min before.
I've added some prints to the command so you can see config.

root@uk_staging-cassandra-03:/etc/medusa# medusa list-backups
StorageConfig(bucket_name='shed', key_file=None, prefix=None, fqdn='uk_staging-cassandra-3', host_file_separator=',', storage_provider='local', api_key_or_username=None, api_secret_or_password=None, base_path='/home', max_backup_age='0', max_backup_count='0', api_profile='default')

**Comment by gruaig** [comment]
That command doesn't make any difference. 
root@uk_staging-cassandra-03:/# medusa build-index
[2019-11-20 13:52:39] WARNING: is ccm : 0
[2019-11-20 13:52:39] INFO: processing uk_staging-cassandra-01
[2019-11-20 13:52:39] INFO: processing uk_staging-cassandra-02
[2019-11-20 13:52:39] INFO: processing uk_staging-cassandra-3
[2019-11-20 13:52:39] INFO: processing uk_staging-cassandra-04
root@uk_staging-cassandra-03:/# medusa -v list-backups --show-all
[2019-11-20 13:52:44] DEBUG: Loading configuration from /etc/medusa/medusa.ini
[2019-11-20 13:52:44] INFO: No backups found in index. Consider running "medusa build-index" if you have some backups
root@uk_staging-cassandra-03:/#

**Comment by adejanovski** [comment]
> Hi
>
>I have changed the path. And here is my structure.
>
>root@uk_staging-cassandra-03:/# medusa restore-node --backup-name
>uk_staging-cassandra-3
>[2019-11-20 15:19:55] ERROR: No such backup
>root@uk_staging-cassandra-03:/# medusa restore-node --backup-name
>/db-snapshots/local/uk_staging-cassandra-3
>[2019-11-20 15:20:04] ERROR: No such backup
>root@uk_staging-cassandra-03:/# medusa restore-node --backup-name
>/db-snapshots/local/uk_staging-cassandra-3/^C
>root@uk_staging-cassandra-03:/# ls /db-snapshots/local/
>index  uk_staging-cassandra-3
>root@uk_staging-cassandra-03:/# ls
>/db-snapshots/local/uk_staging-cassandra-3/
>2019112014  data
>root@uk_staging-cassandra-03:/# ls
>/db-snapshots/local/uk_staging-cassandra-3/*
>/db-snapshots/local/uk_staging-cassandra-3/2019112014:
>meta
>
>/db-snapshots/local/uk_staging-cassandra-3/data:
>main  orders  shared  system  system_auth  system_schema
>root@uk_staging-cassandra-03:/#
>
>Sean

Could you share the content of `/db-snapshots/local/index` and the subdirectories there. Also, I'd be interested by `/db-snapshots/local/uk_staging-cassandra-3/2019112014/meta/*`

**Comment by gruaig** [comment]
>root@uk_staging-cassandra-03:/db-snapshots# cd local/
root@uk_staging-cassandra-03:/db-snapshots/local# ls
index  uk_staging-cassandra-3

>root@uk_staging-cassandra-03:/db-snapshots/local# ls index/
backup_index  latest_backup

>root@uk_staging-cassandra-03:/db-snapshots/local# ls index/*
index/backup_index:
2019112014

>index/latest_backup:
uk_staging-cassandra-3

>root@uk_staging-cassandra-03:/db-snapshots/local# ls index/*/*
index/backup_index/2019112014:
differential_uk_staging-cassandra-3		      manifest_uk_staging-cassandra-3.json  started_uk_staging-cassandra-3_1574261771.timestamp
finished_uk_staging-cassandra-3_1574262014.timestamp  schema_uk_staging-cassandra-3.cql     tokenmap_uk_staging-cassandra-3.json

>index/latest_backup/uk_staging-cassandra-3:
backup_name.txt  tokenmap.json
root@uk_staging-cassandra-03:/db-snapshots/local# 

>root@uk_staging-cassandra-03:/db-snapshots/local# ls /db-snapshots/local/uk_staging-cassandra-3/2019112014/meta/*

>/db-snapshots/local/uk_staging-cassandra-3/2019112014/meta/differential
>/db-snapshots/local/uk_staging-cassandra-3/2019112014/meta/schema.cql
>/db-snapshots/local/uk_staging-cassandra-3/2019112014/meta/manifest.json 
>/db-snapshots/local/uk_staging-cassandra-3/2019112014/meta/tokenmap.json
>root@uk_staging-cassandra-03:/db-snapshots/local# 

So it seems to have all the files based on the documentation.

**Comment by adejanovski** [comment]
ok I see what's wrong 😭 
Your nodes have an `_` in their hostnames, which breaks some naming conventions we use for the meta files in the backup index... See [here](https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/storage/__init__.py#L156). Not very proud of this actually 😅 

We should be able to fix it though, with some regex magic instead of dumb splits.

**Comment by gruaig** [comment]
Actually I should have picked up on that:). Thanks.

**Comment by gruaig** [comment]
Hey.

So I've changed my host names. Also deleted the backups and took new ones.
I checked  the whole folder structure there is no longer any "_".  Still it
didn't find them :S awks

**Comment by adejanovski** [comment]
Awesome, we still need a fix for fqdns with `_` in it.
Also, since your backup locations aren't connected together in the cluster, you'll have some weird behaviors. For example, all backups will be marked as incomplete, and you won't be able to perform cluster wide restores.

Keeping the ticket open until we fix the `_` problem.

**Comment by rzvoncek** [comment]
I'm on this
