### ISSUE TITLE
Write a design document for the various restore scenarios

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-medusa#128]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952134)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-270) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-270

**Comment by rzvoncek** [comment]
I've managed to map out quite some of the restore scenarios:
<img width="1358" alt="Screenshot 2020-06-09 at 10 58 25" src="https://user-images.githubusercontent.com/2589903/84121750-390cf200-aa40-11ea-947a-cc2105ac6055.png">
The next step is to go through them and see which ones work and which ones don't.
