### ISSUE TITLE
Issue with Prefix parameter when using s3 storage

### ISSUE THREAD

**Issue by baileygm** [thelastpickle/cassandra-medusa#13]
I've started experimenting with medusa and noticed that if the prefix parameter is set to allow multi-tenancy within the same bucket the backup is reported as invalid

In the example below I have set the prefix to "medusa"  and for each sstable the verification output reports two messages as below:-

>[medusa/cassandra01dev/backup/data/system_schema/views-9786ac1cdd583201a7cdad556410c985/md-45-big-Index.db] exists in storage, but not in manifest

>[cassandra01dev/backup/data/system_schema/views-9786ac1cdd583201a7cdad556410c985/md-45-big-Index.db] Doesn't exists

Once I commented out the prefix setting in medusa.ini the backup verified correctly

>Validating backup ...
> - Completion: OK!
> - Manifest validated: OK!!

**Comment by adejanovski** [comment]
Good catch, thanks for reporting! 
We need to fix this for sure.

**Comment by liwy00** [comment]
in download.py file, download_data ln 32:
srcs = ['{}{}'.format(storage.storage_driver.get_path_prefix(backup.data_path), obj['path'])
                for obj in section['objects']]

Basically the class S3Storage(AbstractStorage) in s3_storage.py doesn't overwrite get_path_prefix method from super class and return "", so that the prefix get lost in multi-cluster scenario.

**Comment by liwy00** [comment]
Also in resotre_node.py, the restore_node_sstableloader method, line 129:
        differential_blob = storage.storage_driver.get_blob(
            os.path.join(fqdn, backup_name, 'meta', 'differential'))

the prefix from "config.storage.prefix" was not "joined" in the above path, so that no file can be downloaded from s3. You'll see a lot of 404 in the medusa log on each node
