### ISSUE TITLE
Implement gRPC service layer

### ISSUE THREAD

**Issue by jsanda** [thelastpickle/cassandra-medusa#137]
There is ongoing discussion in #24 about using Medusa in Kubernetes. One of the things that needs to be done is to provide a _service_ layer, presumably HTTP-based. #88 was already opened for this and I started doing some investigation into creating a REST service for Medusa. I am instead going to build a gRPC service.

I think that RPC-style endpoints map more naturally to Medusa commands than a REST API would. This makes me think I will be able to develop a gRPC service layer more quickly than I could develop a REST service layer.

The goal of this ticket is to provide service endpoints that are be needed for Kubernetes use cases. 

The goal is **not** to simply expose all Medusa functionality, commands, etc via gRPC. Consider the `restore-cluster` command as an example. Medusa takes on the role of orchestrator with `restore-cluster`.  We do not need Medusa to assume the role of orchestrator in Kubernetes; therefore, the gRPC service does not need to provide an endpoint for `restore-cluster`.

The gRPC service also needs to expose a health check endpoint. The process for implementing a health check endpoint is described in https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-273) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-273

**Comment by julienlau** [comment]
I don't know if auth design is layed out, but if so I'm wondering: will it be based on cassandra auth ? K8S auth ?
Will it also work without TLS ?

**Comment by jsanda** [comment]
Closing since this is done.
