### ISSUE TITLE
use default values for undefined properties in cassandra.yaml

### ISSUE THREAD

**Issue by jsanda** [thelastpickle/cassandra-medusa#152]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952122)

Medusa raises an error if any of the following properties are not set in cassandra.yaml:

* data_file_directories
* commitlog_directory
* saved_caches_directory

Is there a reason why Cassandra default values cannot be used?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-281) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-281

**Comment by rzvoncek** [comment]
It's very unlikely that these 3 settings are not set. Moreover, in k8ssandra, we have pretty uniform environment where these are always set. We don't think duplicating Cassnadra's code in Medusa is all too useful.
