### ISSUE TITLE
Manifest validation fail - Wrong checksum GCS

### ISSUE THREAD

**Issue by matdupont** [thelastpickle/cassandra-medusa#161]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952108)

Hi,

I'm actually backuping 3 cassandra nodes and get some troubles.
When i launch a `medusa -v verify backup-name=cassandra-20200617`, i get :

```
[2020-06-17 19:07:32,049] ERROR: Expected 9dae3bbba396afb729628d5d70bcd124 but got e3ef76373ac9050cb2b03f9cf3a3e684 for cassandra02/cassandra-20200617/data/keyspace/table1-d3c9c2c0a25011ea8d9407bc41823af5
[2020-06-17 19:07:32,050] ERROR: Expected 8e1f591254fbdbd78d20ca52bde98afb but got f7d158f19aaaab08cfa6dcc8c8f5609d for cassandra02/cassandra-20200617/data/keyspace/table2-d3c221a0a25011ea8d9407bc41823af5

Validating cassandra-20200617 ...
- Completion: OK!
- Manifest validation: Failed!
  - [cassandra02/cassandra-20200617/data/keyspace/table1-d3c9c2c0a25011ea8d9407bc41823af5] Wrong checksum
  - [cassandra02/cassandra-20200617/data/keyspace/table2-d3c221a0a25011ea8d9407bc41823af5] Wrong checksum
```

```
When restoring :
[2020-06-15 18:07:34,733] ERROR: Some nodes failed to restore. Exiting
```

I'm using medusa 0.6 and Google Cloud Storage.
I'm backuping them sequentially

```
cassandra-20200617
- Started: 2020-06-17 01:30:02, Finished: 2020-06-17 01:36:54
- 3 nodes completed, 0 nodes incomplete, 0 nodes missing
- 1934 files, 118.99 MB
```

It tooks 2 min per nodes and i'm planning to do it with pssh after.
When the backup is performing, it might be some activity on cassandra at the same time, could it be the cause of my issues ?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-286) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-286

**Comment by matdupont** [comment]
Hi,

Little update. I'm backuping now with pssh but still got the issue.
I tried to clean the bucket before my backup and it worked !!

````
Validating cassandra-20200621 ...
- Completion: OK!
- Manifest validated: OK!!
````

So i try to let the backup on the bucket and doing it again and it failed !
It's working only if the bucket is empty.

I think i have to find a solution to separate each backup from another to fix it at the moment.

**Comment by CZmikee** [comment]
Any estimate when this might be addressed? I am having same issue in my env. Same as reported by matdupont - GCS storage uploads, when there is no backup, all works fine. Running backup succeeds, verifying it as well. 
When there is any backup already existing, the backup itself succeeds, but verify fails on manifest validation that  "Blob different"

cassandra-medusa Version: 0.7.1 installed via pip3

**Comment by rzvoncek** [comment]
Hello @matdupont! I'm doing some grooming of the oldest issues we have and stumbled upon this.
Over the years, we've iterated on the storage implementation a lot, and this probably got resolved. 
I'll soon go ahead and close this as stale, but please let us know if you still have this or other issues.
