### ISSUE TITLE
Cannot use AWS Stockholm eu-north-1 without latest libcloud

### ISSUE THREAD

**Issue by michaelsembwever** [thelastpickle/cassandra-medusa#17]
This got fixed in libcloud commit (2aad12a)[https://github.com/apache/libcloud/commit/2aad12ad42eb67a293a7bf675ce65a8e31c951a5].

Once released, cassandra-medusa can upgrade to it, allowing eu-north-1 (and other new aws regions) to be used.

In the meantime the workaround is to manually install that libcloud version by doing 
```
pip3 install git+https://github.com/apache/libcloud.git@2aad12ad42eb67a293a7bf675ce65a8e31c951a5 --force-reinstall
```

**Comment by arodrime** [comment]
@michaelsembwever I think this is now in libcloud (2.7.0+): https://github.com/apache/libcloud/blob/v2.8.0/CHANGES.rst#user-content-storage-1

Let's upgrade dependencies and close this ticket? Would you be happy with this?

**Comment by arodrime** [comment]
@michaelsembwever / @adejanovski does this change / PR look good to you?

**Comment by arodrime** [comment]
I merged the version bump for libcloud fyi @michaelsembwever. Closing this issue. Feel free to reopen if you face the issue again.
