### ISSUE TITLE
Performing backups to Azure

### ISSUE THREAD

**Issue by ilhanadiyaman** [thelastpickle/cassandra-medusa#171]
Is it possible to backup Azure Blob Storage?

**Comment by arodrime** [comment]
We did not implement it yet. We are using libcloud under the hood to handle distinct cloud environment.

If you feel like doing it, we would be happy to review and quickly merge your pull request.
If not, I'm quite sure we will implement the support for Microsoft Azure at some point. I'm not sure when though.

**Comment by ilhanadiyaman** [comment]
Thanks @arodrime. I'll take a look how I can use libcloud to implement Azure Blob Storage connection.

**Comment by arodrime** [comment]
Folks, this is a WIP, please do not review before getting green lights from @ilhanadiyaman, on his explicit demand :).

Thanks for doing this work!

**Comment by ilhanadiyaman** [comment]
#219 fixes this issue. Closing this.
