### ISSUE TITLE
Problem with restore only one keyspace with option --keyspace

### ISSUE THREAD

**Issue by TryToWork** [thelastpickle/cassandra-medusa#173]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952105)

Hello,

I have a problem with the option --keyspace which is supposed to restore only the keyspace passed in parameter according to the wiki.

 Restoring only one keyspace isn't valid, the keyspace is well restore but this method has an impact on the other keyspaces:

* if a new keyspace which did not exist at the time of the backup is present, this keyspace disappears ...
* if we have another keyspace that existed at the time of the backup it is restored too at the time of the backup

Cordially

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-288) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-288

**Comment by sigalits** [comment]
The --keyspace option doesn't seem to work,  all keyspaces are being restored , as if the parameter is ignored.
would it be fixed any time soon?

**Comment by rzvoncek** [comment]
This got fixed in https://github.com/thelastpickle/cassandra-medusa/pull/221, about 4 months after this issue was opened.
