### ISSUE TITLE
Restore Failing with Version 0.7.0

### ISSUE THREAD

**Issue by HanumanthPrasad** [thelastpickle/cassandra-medusa#175]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952104)

Cluster restore is failing with the below error message. This is the only log that is getting printed. But the same restore is working with version 0.6.0 without any issues.

ERROR: Cannot keep system_auth when restoring in-place. It would be overwritten

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-290) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-290

**Comment by arodrime** [comment]
Discussed here (FTR) --> https://the-asf.slack.com/archives/C0111B5KADA/p1595484832028100

**Comment by rzvoncek** [comment]
Stumbled upon this while grooming the oldest tickets. Since so much time has passed, I'm marking this as stale, and will close later.
