### ISSUE TITLE
TLS1.0 is deprecated in most places

### ISSUE THREAD

**Issue by mkramer07** [thelastpickle/cassandra-medusa#176]
Really just want to upgrade the tls version that's pulled from ssl to now use 1.2 instead of 1.0. Most places have already migrated to 1.2 and not even sure how many people are using 1.0 these days.

**Comment by mkramer07** [comment]
It's a pretty quick and easy fix, I have running locally with just changing `PROTOCOL_TLSv1` to `PROTOCOL_TLSv1_2`

**Comment by arodrime** [comment]
@mkramer07 feel free to open a PR if you'd like. Either ways, I'll check it as soon as possible. Thanks for the feedback.

**Comment by ernstae** [comment]
I'd like to adopt Medusa, but TLS 1.2 is non-negotiable in my world.  Any movement on this feature?

**Comment by adejanovski** [comment]
Yes, we're working on this in conjunction with some work that is being done on Cassandra 4.0.
We should update Medusa soon to support a different version of TLS.

**Comment by mkcello96** [comment]
HI all, I put in a PR here https://github.com/thelastpickle/cassandra-medusa/pull/260 (I work with @ernstae). Ready for review, hopefully can just be a replacement for the work you have slated to be done.  
@arodrime @adejanovski @mkramer07
