### ISSUE TITLE
restore-node on non-seed cannot detect other nodes being up because of unexpected nc output

### ISSUE THREAD

**Issue by bolteddown** [thelastpickle/cassandra-medusa#178]
When restoring, non-seed nodes will never detect that Cassandra has started on the seed nodes. They will timeout and never start.

Medusa: 0.7.0
OS: CentOS 7.5
ncat: 7.5

The cause of this error is that the output of `nc` may be different, likely between versions. The code found [here](https://github.com/thelastpickle/cassandra-medusa/blob/9a4d1ae301abbe1c8ee440d5604033db3812f17e/medusa/cassandra_utils.py#L635) is looking for the word 'succeeded' to indicate that the seed node has started. You can see in the output below that that word is not included in our case.

```
$ nc -vz <ip addr> 9042
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to <ip addr>:9042.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
```

The fix may be to look for 'succeeded' OR 'Connected'.

**Comment by arodrime** [comment]
Fix released in [v0.7.1](https://github.com/thelastpickle/cassandra-medusa/releases/tag/v0.7.1)
