### ISSUE TITLE
Add functionality to delete specific backups

### ISSUE THREAD

**Issue by michaelsembwever** [thelastpickle/cassandra-medusa#18]
Backups may be created by testing or fail and remain in an incomplete state. Such backups are useless and wasting resources and money.

There should be a way to delete such backups without having to go into the s3 buckets are manually delete stuff (which is not trivial because of the layout medusa creates there)

**Comment by arodrime** [comment]
This was solved per https://github.com/thelastpickle/cassandra-medusa/pull/65. Closing the issue!
