### ISSUE TITLE
pyinstaller - how to

### ISSUE THREAD

**Issue by nutellinoit** [thelastpickle/cassandra-medusa#180]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952103)

Hello!

First of all thank you for this awesome tool.

I have a question on how to package it using pyinstaller. I can't use python pip to install the "offline" version.

Someone has done it?

Thank you

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-291) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-291

**Comment by nutellinoit** [comment]
I'm sorry, but I'm not using Cassandra in production anymore, and I don't remember what I did for this issue.

**Comment by rzvoncek** [comment]
Hey! No worries, thanks for letting us know!
