### ISSUE TITLE
Need to have --region and --debug parameter for aws s3 cp

### ISSUE THREAD

**Issue by chidhambaram7** [thelastpickle/cassandra-medusa#184]
Hi,

We have decided to use AWS S3 as backup location for our clusters. So, we use AWS VPC S3 endpoint to upload and download data from S3. To use VPC endpoint, I have to sepcify `--region` parameter along with `aws s3 cp`. As of now, I have modified `awscli.py` file manually with the required parameter. 
Please consider to have more parameter to append to `aws s3 cp` command.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-292) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-292

**Comment by sigalits** [comment]
I have also came across that issue. will be happy to get it resolved

**Comment by adejanovski** [comment]
The `--region` param was added in #272
