### ISSUE TITLE
Local backups not connected

### ISSUE THREAD

**Issue by dataindataout** [thelastpickle/cassandra-medusa#21]
Environment:
3-node Cassandra cluster in Docker
Debian GNU/Linux 9 (stretch)
Python 3.7.5

I have an ops container and 3 Cassandra containers. All else appears to be working without issue (this is a standard cluster I use for testing, now with medusa added), but when doing medusa backups to local storage, the backups on each node aren't connected.

From the ops container, I run:
`cstar run --command="medusa backup --backup-name=testbackup3" --seed-host=172.16.238.2 --strategy=all`

All ends well:
```
+++
3 done, 0 failed, 0 executing
```

But restore does not work, reporting that backups are incomplete. On each Cassandra node, the backups have run but aren't connected. Each node has its own backup and reports missing for the other 2 nodes. Here is an example of the status:
```
medusa status --backup-name testbackup3
testbackup3 [Incomplete!]
- Started: 2019-11-25 16:09:24, Finished: never
- 1 nodes completed, 0 nodes incomplete, 2 nodes missing
- Missing nodes:
    DC1C1.cassandra-medusa_myring
    DC1C3.cassandra-medusa_myring
- 193 files, 355.51 KB
```

Here's the only section changed from the default medusa.ini:
```
[storage]
storage_provider = local
; storage_provider should be either of "local", "google_storage" or the s3_* values from
; https://github.com/apache/libcloud/blob/trunk/libcloud/storage/types.py
bucket_name = testbackup20191124
;key_file = <JSON key file for service account with access to GCS bucket or AWS credentials file (home-dir/.aws/credentials)>
base_path = /home
;prefix = <Any prefix used for multitenancy in the same bucket>
;fqdn = <enforce the name of the local node. Computed automatically if not provided.>
;max_backup_age = <number of days before backups are purged. 0 means backups don't get purged by age (default)>
;max_backup_count = <number of backups to retain. Older backups will get purged beyond that number. 0 means backups don't get purged by count (default)>
; Both thresholds can be defined for backup purge.
```

**Comment by adejanovski** [comment]
Hi @dataindataout,

are you backing up to a directory that is shared by all the nodes in the cluster?
The "local" storage provider is meant to be using a shared storage so that each node can see the other nodes backups and we have a centralized place where backups are stored for the whole cluster.
The base path you're using seems to indicate that it's not a shared folder.

**Comment by dataindataout** [comment]
Thank you, @adejanovski. I had assumed too much magic.

Having a shared backup folder allowed each node to see all the backups:
```
medusa status --backup-name testbackup5
testbackup5
- Started: 2019-11-25 17:43:21, Finished: 2019-11-25 17:43:57
- 3 nodes completed, 0 nodes incomplete, 0 nodes missing
- 408 files, 476.47 KB
```

I did have to alter /etc/hosts to specify the hostname for each node, so the backup folder names matched the hostnames. This is a testing artifact, not likely to be found in production, but mentioning it here in case anyone else runs into the same problem.

**Comment by adejanovski** [comment]
Thanks @dataindataout, closing the ticket.
