### ISSUE TITLE
Using offline s3 storage such as minio

### ISSUE THREAD

**Issue by DrissiReda** [thelastpickle/cassandra-medusa#236]
Is it possible to use another s3 storage than classic aws? I need to upload my backups remotely to an offline remote storage, I've seen in the code that the [storage] section supports the option "host" but it seems that the storage_provider s3 just ignores it.

Can anyone point me into the right direction as to how I can achieve this?

**Comment by adejanovski** [comment]
Hi @DrissiReda,

I don't think you can achieve this through configuration only.
You may want to take a look at [this PR](https://github.com/thelastpickle/cassandra-medusa/pull/226) which added support for IBM Cloud Storage to guide your implementation. IBM Cloud Storage is compatible with S3, including with the awscli but it requires to add custom endpoint urls depending on the region.
You'll have to create a new libcloud provider that will inherit from the S3 provider and then create a MinioStorage class under `medusa/storage`.

**Comment by DrissiReda** [comment]
Thanks @adejanovski I made a PR for it.

**Comment by jsanda** [comment]
Hi @DrissiReda,

It is by design that nodetool is not in image used to run the gRPC service. When Medusa is run inside Kubernetes, it won't have access to nodetool. It makes REST api requests to the management-api (used by cass-operator) or to Jolokia for creating snapshots.

The image is really only intended for use inside of Kubernetes. I would not expect it to work outside of a Kubernetes deployment.

**Comment by burmanm** [comment]
I think it would make more sense to just allow S3 to use the host/port or endpoint_url. And then merge the IBM Cloud to that one and use the same for Minio. All those S3 compatible storages should work that way.

**Comment by DrissiReda** [comment]
You would need to make the libcloud driver for it as well.

**Comment by burmanm** [comment]
Why? Just set the driver to be s3 in the config.

**Comment by Skunnyk** [comment]
We have a custom s3 infra/endpoint, so it would be marvelous to be able to connect to it simply by overriding some variables.
With `awscli` for example, you can override the endpoint with the https://pypi.org/project/awscli-plugin-endpoint/ plugin.

Reimplementing a "driver" for every compatible s3 provider is not really "kiss". But maybe it's tied to how `libcloud` works…

**Comment by adejanovski** [comment]
There are two sides to this:
- Libcloud in its current design won't allow us to support a new S3 compatible backend without creating a specific subclass of the S3 driver.
- Medusa could, I hope, easily unify the S3 compatible drivers into a single class. This would allow to remove a lot of code duplication. It supposes though that the endpoint is all that changes between implementations (which is hopefully the case).

The latter is something we should be able to tackle fairly easily I think, and we could create ourselves a generic S3 libcloud driver that would take the endpoint and region as inputs.

btw @DrissiReda, have you seen this? https://github.com/apache/libcloud/blob/trunk/libcloud/storage/drivers/minio.py
Seems like Minio support was recently added to libcloud? We shouldn't need [this file](https://github.com/thelastpickle/cassandra-medusa/blob/2ed5e5b5710112d3c898889197b97c1b6dd85fa6/medusa/libcloud/storage/drivers/minio.py) anymore in your PR then.

**Comment by DrissiReda** [comment]
I've seen it but we'll still need it: refer to https://github.com/apache/libcloud/issues/1539

The region needs to be set,  the file you linked hardcodes the region to "" and minio needs it to be "us-east-1" otherwise awscli complains.

**Comment by adejanovski** [comment]
Gotcha! Thanks for the pointer.

**Comment by adejanovski** [comment]
Available in 0.9

**Comment by DrissiReda** [comment]
I haven't checked this in a while, thank you very much alexander !
