### ISSUE TITLE
clean_path fails with mounted file systems

### ISSUE THREAD

**Issue by baileygm** [thelastpickle/cassandra-medusa#26]
The clean path command fails if the folder to be wiped is a docker volume mount

Changing
- subprocess.check_output(['sudo', '-u', p.owner(), 'rm', '-rf', str(p)])
to
- subprocess.check_output(['sudo', '-u', p.owner(), 'rm', '-rf', str(p) + '/*'])
should allow the folder to be cleared successfully

**Comment by arodrime** [comment]
Hello @baileygm, thanks for the feedback on this branch.

I'm looking into it now.

**Comment by arodrime** [comment]
If we do just this, the download directory during a restore would remain. That would leave an empty directory there.

What's the exception you have? Maybe catching it would be a good way to handle different cases. When the folder can be removed we do so, when this fails, we try to clean using the suggested `subprocess.check_output(['sudo', '-u', p.owner(), 'rm', '-rf', str(p) + '/*'])`.

What are your thoughts on this @adejanovski / @baileygm ?

**Comment by arodrime** [comment]
Another thought, are you mounting each of these folders individually? I mean, is this the root of mounting  point? 

If so, isn't it easier to use a parent folder as the mounting point? 🤔

**Comment by baileygm** [comment]
Hi @arodrime 
I see your point regarding empty directories remaining after a restore however that doesn't concern me too much as I don't expect to be restoring data very often
I'll try your suggestion of mounting the parent folder as that should work - I had considered this but hoped to make the least changes possible in our production environment

**Comment by baileygm** [comment]
Changing the mount point resolved the issue so there's no need for code changes
Thanks for the rapid response
