### ISSUE TITLE
Allow for using Management API to manage snapshots in k8s deployments

### ISSUE THREAD

**Issue by emerkle826** [thelastpickle/cassandra-medusa#262]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952077)

As of version 0.1.17, the [Management API for Apache Cassandra](https://github.com/datastax/management-api-for-apache-cassandra) now has snapshot management endpoints.

Since #223 was merged and added gRPC to Medusa, in a Kubernetes deployment, Medusa uses Jolkia to manage snapshots in the Cassandra pod as there is no access to nodetool in the Cassandra pod from the Medusa pod. The Management API now provides for REST endpoints to create, delete and retrieve snapshots. Medusa integration with these endpoints would be preferred over Jolokia.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-246) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-246

**Comment by rzvoncek** [comment]
Fixed in https://github.com/thelastpickle/cassandra-medusa/pull/237
