### ISSUE TITLE
The k8s Docker image needs to run as non-root

### ISSUE THREAD

**Issue by jsanda** [thelastpickle/cassandra-medusa#279]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952070)

We now have support for running Cassandra in k8ssandra as a non-root user (see https://github.com/datastax/management-api-for-apache-cassandra/pull/59). I am in the process making changes to get everything running as non-root. 

Here is the security context I am using for the Cassandra pods:

```yaml
  securityContext:
    fsGroup: 999
    runAsGroup: 999
    runAsUser: 999
```

The `medusa` container fails with this error:

```
$ kubectl logs test-dc1-default-sts-1 -c medusa
MEDUSA_MODE = GRPC
sleeping for 0 sec
Starting Medusa gRPC service
DEBUG:root:sleeping for 0 sec
[2021-02-06 19:06:20,823] DEBUG: sleeping for 0 sec
INFO:root:Init service
[2021-02-06 19:06:20,826] INFO: Init service
DEBUG:root:Reading AWS credentials from /etc/medusa-secrets/medusa_s3_credentials
[2021-02-06 19:06:20,827] DEBUG: Reading AWS credentials from /etc/medusa-secrets/medusa_s3_credentials

[Errno 13] Permission denied: '/.aws'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/medusa/service/grpc/server.py", line 158, in <module>
    medusa_pb2_grpc.add_MedusaServicer_to_server(MedusaService(config), server)
  File "/app/medusa/service/grpc/server.py", line 45, in __init__
    self.storage = Storage(config=self.config.storage)
  File "/app/medusa/storage/__init__.py", line 72, in __init__
    self.storage_driver = self._connect_storage()
  File "/app/medusa/storage/__init__.py", line 87, in _connect_storage
    s3_storage = S3Storage(self._config)
  File "/app/medusa/storage/abstract_storage.py", line 39, in __init__
    self.driver = self.connect_storage()
  File "/app/medusa/storage/s3_storage.py", line 135, in connect_storage
    self.set_upload_bandwidth()
  File "/app/medusa/storage/s3_storage.py", line 256, in set_upload_bandwidth
    self.config.transfer_max_bandwidth,
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['aws', 'configure', 'set', 'default.s3.max_bandwidth', '50MB/s']' returned non-zero exit status 255.
```

I think the issue is that the `awscli` package is installed as root. Note I am referring to `k8s/Dockerfile`.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-237) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-237

**Comment by jsanda** [comment]
@burmanm can you take a look at this?

**Comment by jsanda** [comment]
We have the following in `k8s/Dockerfile`:

```
groupadd -r cassandra --gid=999 && useradd -r -g cassandra --uid=999 cassandra
```

From a security standpoint I think it would be better to use a different uid for Medusa. I think we want the same gid though as the Cassandra user.

**Comment by jsanda** [comment]
I want to provide some more context on this. https://github.com/datastax/management-api-for-apache-cassandra/pull/43 added support for non-root Cassandra images. That also includes a 4.0-beta4 image. We only have a non-root image for 4.0-beta4.

In k8ssandra I can only get non-root Cassandra containers to work when Medusa is disabled. See my work in https://github.com/k8ssandra/k8ssandra/pull/336. I wound up having to use a different SecurityContext for the `medusa` container to get it to run, but doing causes Cassandra to fail to start.

Here is some helpful background reading:

* https://github.com/kubernetes/kubernetes/issues/2630
* https://engineering.bitnami.com/articles/running-non-root-containers-on-openshift.html

**Comment by rzvoncek** [comment]
We now have this https://github.com/thelastpickle/cassandra-medusa/blame/master/k8s/Dockerfile#L53.

I'd say this issue is resolved.

**Comment by burmanm** [comment]
Yes, for this exact topic "run as non-root" we indeed do. But Medusa images are behind our other images in that they can use any securityContext right now (with some group restrictions, but uid is quite freely chosen). I'm not sure if these Medusa images still work if I run the Cassandra container as user ``123456`` instead of the default 999. This is probably something we need to investigate, but perhaps that requires a new ticket?

**Comment by rzvoncek** [comment]
Ok, well, then let's just close this one here, and we can open another one somewhere else once it crosses our path again.
