### ISSUE TITLE
Google Cloud integration should use Python directly

### ISSUE THREAD

**Issue by burmanm** [thelastpickle/cassandra-medusa#288]
The Google Cloud Storage libraries are actually Python, but the way Medusa uses them is silly. It spawns a subprocess to run a shell command, that then starts a Python process which then runs the Google Cloud's Python code and then returns back to the Medusa's Python.

This means multiple Python interpreters on top of each other and no real integration. Both gsutil and gcloud are bash scripts that execute Python. Instead, the integration should use Python libraries directly to do the uploads / downloads / ls.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-230) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-230

**Comment by rzvoncek** [comment]
We are doing this now, closing.
