### ISSUE TITLE
Incomplete backup

### ISSUE THREAD

**Issue by akap97** [thelastpickle/cassandra-medusa#297]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952064)

am trying to backup 2 node cassandra cluster using medusa:

medusa backup --backup-name=test
I am running this command on both the nodes simultaneously. However, medusa list-backups shows:

test (started: 2021-02-28 15:22:43, finished: Incomplete [0 of 2 nodes finished])

on running medusa verify --backup-name test, it shows:

Validating test ...

Completion: Not complete!
[192.168.146.167] Backup started at 1614525763, but not finished yet
[192.168.231.3] Backup started at 1614525765, but not finished yet [2021-02-28 15:27:24,814] ERROR: Unable to read manifest from storage [2021-02-28 15:27:24,829] ERROR: Unable to read manifest from storage
Manifest validated: OK!!

my medusa.ini file :

[cassandra]
stop_cmd = /home/ubuntu/apache-cassandra-3.11.10/bin/cassandra stop
start_cmd = /home/ubuntu/apache-cassandra-3.11.10/bin/cassandra start
config_file = /home/ubuntu/apache-cassandra-3.11.10/conf/cassandra.yaml
;cql_username = <username>
;cql_password = <password>
;nodetool_username =  <my nodetool username>
;nodetool_password =  <my nodetool password>
;nodetool_password_file_path = <path to nodetool password file>
nodetool_host = 192.168.146.167
nodetool_port = 7199
;certfile= <Client SSL: path to rootCa certificate>
;usercert= <Client SSL: path to user certificate>
;userkey= <Client SSL: path to user key>
;sstableloader_ts = <Client SSL: full path to truststore>
;sstableloader_tspw = <Client SSL: password of the truststore>
;sstableloader_ks = <Client SSL: full path to keystore>
;sstableloader_kspw = <Client SSL: password of the keystore>

; Enable this to add the '--ssl' parameter to nodetool. The nodetool-ssl.properties is expected to be in the normal location
;nodetool_ssl = true

; Command ran to verify if Cassandra is running on a node. Defaults to "nodetool version"
check_running = /home/ubuntu/apache-cassandra-3.11.10/bin/nodetool

resolve_ip_addresses = False

[storage]
storage_provider = s3_ap_south

; Name of the bucket used for storing backups
bucket_name = ocp-file-xchange

; JSON key file for service account with access to GCS bucket or AWS credentials file (home-dir/.aws/credentials)
key_file = /etc/medusa/medusa-s3-credentials

; Any prefix used for multitenancy in the same bucket
prefix = cluster1

[ssh]
;username = ubuntu
;key_file = ~/cert.pem
;port = <SSH port for use for restoring clusters. Default to port 22.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-226) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-226

**Comment by rzvoncek** [comment]
Hi @akap97 , I know it's been very long. Still, did you manage to resolve this?
