### ISSUE TITLE
Log file or log streaming configuration

### ISSUE THREAD

**Issue by baileygm** [thelastpickle/cassandra-medusa#30]
Is there any simple way to configure file based logging or the streaming of the log messages from the medusacli to a centralised logging system ?

It would be useful to be able to set up alerting based on these message to ensure that the backup processes have been successful.

**Comment by nicholasamorim** [comment]
I've added _basic_ support to file logging in #36 - hopefully, they'll merge it in.

**Comment by baileygm** [comment]
Nice one - can you confirm that the value set for "--log-file" in your pull request should be set to the full path of the log file ?

**Comment by nicholasamorim** [comment]
It works like a normal path, if you provide a path that doesn't start with `/` it is relative, otherwise it is absolute.

**Comment by nicholasamorim** [comment]
Just to register here that the scope of #36 has changed and the PR now also deals with setting up logging configuration in the `medusa.ini` file with multiple option supported.

**Comment by baileygm** [comment]
@nicholasamorim Yes, I was meaning something like syslog or journald but what you are implementing will work well for us as we are already using filebeat to stream logs from cassandra to elasticsearch so I will simply use it to also tail the medusa logs as well

**Comment by nicholasamorim** [comment]
#36 has been merged and adds logging-to-file support.

@adejanovski I think this can be closed.

**Comment by baileygm** [comment]
@adejanovski 
Could you tell me when you plan to create a new release of medusa which includes this functionality ?

**Comment by adejanovski** [comment]
Hi @baileygm ,

I'm finishing the debian packaging and then I'll cut out a new release that includes file logging.
I should do it within a week from now.
