### ISSUE TITLE
Does Medusa support differential or incremental backups?

### ISSUE THREAD

**Issue by m934030039** [thelastpickle/cassandra-medusa#300]
https://github.com/thelastpickle/cassandra-medusa/wiki mentioned Medusa offers "Full or incremental backups".
But, my understanding is Medusa supports differential NOT incremental backups?

**Comment by adejanovski** [comment]
correct, Medusa supports differential backups, not incremental.
I'll fix the wiki, thanks!

**Comment by adejanovski** [comment]
Fixed
