### ISSUE TITLE
Add support for setting tokens during restore when running in Kubernetes

### ISSUE THREAD

**Issue by jsanda** [thelastpickle/cassandra-medusa#303]
In k8ssandra restoring to a new cluster currently does not work (see https://github.com/k8ssandra/k8ssandra/issues/70). There are a couple issues that need to be resolved. One of those issues is that Medusa does not update tokens in cassandra.yaml when running in Kubernetes. Here is the relevant code from the `restore_node_locally` function in `medusa/restore_node.py`:

```python
    if not medusa.utils.evaluate_boolean(config.kubernetes.enabled):
        if seeds is not None:
            wait_for_seeds(config, seeds)
        else:
            logging.info('No --seeds specified so we will not wait for any')

        # Start up Cassandra
        logging.info('Starting Cassandra')
        # restoring in place retains system.local, which has tokens in it. no need to specify extra
        if in_place:
            cassandra.start_with_implicit_token()
        else:
            cassandra.start(tokens)
```
The code that updates cassandra.yaml happens in `cassandra.start(tokens)`.  We need to be able to update cassandra.yaml without starting Cassandra (since Medusa won't be able to start Cassandra in Kubernetes).

**Comment by adejanovski** [comment]
A couple of other things that need to be done for a remote restore:

- Disable auto bootstrap
- Prevent restoring the `system.local` table (Haven't checked the code for k8s specific paths so maybe it's already handled).

**Comment by jsanda** [comment]
Thanks for the info @adejanovski.

There does not appear to be any k8s specific paths around `system.local`, so that's good.

**Comment by burmanm** [comment]
Does that system.local need any change?

There's a code that system.local is never restored for not in place: https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/restore_node.py#L283

**Comment by adejanovski** [comment]
No change needed indeed, Medusa already deals with this correctly, including the k8s case.
