### ISSUE TITLE
Incomplete backups found: 3 nodes completed, 1 missing on a 3 node cluster

### ISSUE THREAD

**Issue by oliviercwa** [thelastpickle/cassandra-medusa#305]
Hello,
We are running a 3 node Cassandra cluster with each node owning 100% of the data. 
Medusa is connected to Azure Blob Storage for back-ups.
Here is a capture of a call to nodetool status
```
--  Address   Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.0.4.4  482.51 MiB  256          100.0%            90a29745-334b-4e41-8e6b-0f26f0b0de35  rack1
UN  10.0.4.5  437.43 MiB  256          100.0%            592d1f06-facf-4322-a01b-feb2a09774d0  rack1
UN  10.0.4.6  437.47 MiB  256          100.0%            1f4262c1-f859-4b31-824c-06ac96992751  rack1
```

On each node we have a CRON job that calls medusa backup on each node. When we list the backups (medusa list-backups) we get the following:
```
2021031007 (started: 2021-03-10 07:40:04, finished: Incomplete [3 of 3 nodes finished])
```
A call to medusa status --backup-name 2021031007 shows the following
```
2021031007 [Incomplete!]
- Started: 2021-03-10 07:40:04, Finished: never
- 3 nodes completed, 0 nodes incomplete, 1 nodes missing
- Missing nodes:
    i1
- 5248 files, 1.33 GB
```

On azure blob storage, in the container we see three folders with snapshots in them (one for each node) plus one folder for the index:
```
i1.internal.cloudapp.net
i1c.internal.cloudapp.net
prod-cas-i1b.internal.cloudapp.net
```

What could cause Medusa to think we have 4 nodes ? How do we fix this issue ?

Thank you

**Comment by oliviercwa** [comment]
Thank you for the quick answer.
I have followed this and wierdly enough the folders create are now:
```
10.0.3.4
i1c.internal.cloudapp.net
prod-cas-i1b.internal.cloudapp.net
```

Even though the IP reported by ifconfig -a is 10.0.4.4

Also nodetool status -r gives:
```
--  Address                             Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.0.4.4                            481.81 MiB  256          100.0%            90a29745-334b-4e41-8e6b-0f26f0b0de35  rack1
UN  prod-cas-i1b.internal.cloudapp.net  436.85 MiB  256          100.0%            592d1f06-facf-4322-a01b-feb2a09774d0  rack1
UN  i1c.internal.cloudapp.net           436.9 MiB  256          100.0%            1f4262c1-f859-4b31-824c-06ac96992751  rack1
```

**Comment by adejanovski** [comment]
ok so you're probably dealing with public/private IP issues and Medusa is getting the public IP although Cassandra is broadcasting the private IP.

That's problematic indeed... I guess the only possibility (aside from fixing DNS resolving which could be non trivial) would be to enforce the ip used for the node by adding `--fqdn=<private ip>` for all commands.

I guess one way we could improve this would be to rely on the ip that is broadcasted by the local Cassandra node instead of relying on Python calls to get the local node ip.

**Comment by oliviercwa** [comment]
Thank you. Note that the nodes do not have any publicly exposed IP address. 
What do you mean by public / private ? I am not sure where the 10.0.3.4 comes from honestly. This is really odd and it's not even in the same subnet.

**Comment by oliviercwa** [comment]
Thank you very much for your help. 

Just to close on this, we have resolved the issue in the DNS (two machines had the same name in the network with 2 different IP address). I think your suggestion to rely on the IP that is broadcaster by local Cassandra node would address this and would probably be more robust than ```gethostbyname```.

Anyway, thanks again for your help !
