### ISSUE TITLE
The gRPC server does not handle the SIGTERM signal

### ISSUE THREAD

**Issue by jsanda** [thelastpickle/cassandra-medusa#312]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952056)

I discovered this issue in k8ssandra. The gRPC service which runs in a k8s container does not handle SIGTERM which delays pod termination. I am tracking this in k8ssandra in https://github.com/k8ssandra/k8ssandra/issues/570. Please see it for details.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-218) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-218

**Comment by rzvoncek** [comment]
Closing since https://github.com/k8ssandra/k8ssandra/issues/570 has been solved.
