### ISSUE TITLE
Restore a list of Cassandra nodes failure

### ISSUE THREAD

**Issue by Fredmomo** [thelastpickle/cassandra-medusa#316]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952054)

When switching to use Cassandra medus to fulfill our work for node data restore, we encountered some issues.

When using pssh remotely we are getting timeout issue, when trying the command on one node of Cassandra, we  get

    pssh -H XXXX medusa -vvv restore-node --in-place --no-verify --backup-name 2021031803 --temp-dir /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a
     [1] 06:52:08 [FAILURE] sha8392 Timed out, Killed by signal 9
     When further looking into the timeout issue, we get logs as
     [2021-03-25 02:23:50,113] DEBUG: https://s3.cn-north-1.amazonaws.com.cn:443 "GET /XX/XX/10.44.XX.XX/2021031803/meta/schema.cql?Version=2006-03-01 HTTP/1.1" 200 24005[2021-03-25 02:23:50,114] DEBUG: [Storage] Getting object sre_dev_cass_sha/10.44.79.15/2021031803/meta/tokenmap.json
     [2021-03-25 02:23:50,151] DEBUG: https://s3.cn-north-1.amazonaws.com.cn:443 "HEAD /XX HTTP/1.1" 200 0[2021-03-25 02:23:50,201] DEBUG: https://s3.cn-north-1.amazonaws.com.cn:443 "HEAD /XX/XX/10.44.79.15/2021031803/meta/tokenmap.json HTTP/1.1" 200 0[2021-03-25 02:23:50,202] DEBUG: Downloading /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a/medusa-restore-197b6c82-4cd5-4c5b-b3c2-9d98863c1b3f as single part
     [2021-03-25 02:23:50,254] DEBUG: https://s3.cn-north-1.amazonaws.com.cn:443 "GET /XX/XX/10.44.XX.XX/2021031803/meta/tokenmap.json?Version=2006-03-01 HTTP/1.1" 200 1535[2021-03-25 02:23:50,255] INFO: Stopping Cassandra
    + /usr/bin/nodetool u cassandra -pw <obfuscated> drain+ /usr/bin/nodetool -u cassandra -pw <obfuscated> drainerror: null- StackTrace --java.io.EOFException at java.io.DataInputStream.readByte(DataInputStream.java:267) at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:222) at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161) at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source) at javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(Unknown Source) at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1020) at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:298) at com.sun.proxy.$Proxy8.drain(Unknown Source) at org.apache.cassandra.tools.NodeProbe.drain(NodeProbe.java:371) at org.apache.cassandra.tools.nodetool.Drain.execute(Drain.java:36) at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:244) at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:158)
     + ls -l /var/run/cassandra/cassandra.pidls: cannot access /var/run/cassandra/cassandra.pid: No such file or directory+ sleep 10+ echo -n 'Shutdown Cassandra: 'Shutdown Cassandra: ++ cat /var/run/cassandra/cassandra.pidcat: /var/run/cassandra/cassandra.pid: No such file or directory+ su cassandra -c 'kill 'kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]++ seq 40+ for t in '`seq 40`'+ /etc/init.d/cassandra status+ break+ sleep 5+ echo OKOKBut we can get a successful run of the command on one node for

```export
medusa-wrapper sudo 
medusa -vvv restore-node --in-place --no-verify --backup-name 2021031803 --temp-dir /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a
```

We are running the command on 

```uname
Linux XXXX 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Could you please have a look at the issue?

Thanks

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-213) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-213

**Comment by adejanovski** [comment]
Hi, 

have you tried running `medusa restore-cluster` first? Did it give the same result?
Is it the same user that is used with pssh and when running the restore directly on the node?
Was Cassandra stopped by the pssh command despite the error messages?
Do you have a firewall that could kill ssh connections that haven't had activity for some time?

**Comment by ReturnHttp402** [comment]
Hi @adejanovski 

Thanks for replying. 

> have you tried running medusa restore-cluster first? Did it give the same result?
Yes we used this command, it then found all the nodes in the cluster and then continues to execute the restore node commands. see commands:
```
export LC_ALL=en_US.UTF-8; export LANG=en_US.UTF-8; export https_proxy=http://proxy.XXX:3128; /usr/share/cassandra-medusa/bin/medusa -v --console_log_level 30 restore-cluster --backup-name=2021031803 --seed-target 10.44.XX.XX
```

> Is it the same user that is used with pssh and when running the restore directly on the node?
Yes, we are using root user to execute both commands.

> Was Cassandra stopped by the pssh command despite the error messages?
No, it didn't stop despite the error that appeared.

> Do you have a firewall that could kill ssh connections that haven't had activity for some time?
We are using a proxy to route the request to AWS S3 bucket which keeps running healthily in that time, no other network limitations for ssh.

**Comment by ReturnHttp402** [comment]
Hi @adejanovski 

After re-initialize the node again and test, we are able to proceed with the downloading, but got different errors when shutting down, see
```
[2021-03-25 10:44:19,976] INFO: Stopping Cassandra
nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.
nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.
nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.
nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.```

and the Cassandra process is not stopped, see
```ps axu|grep cassan
422       7131 27.8 54.8 35751548 33994612 ?   Sl   10:39   0:19 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el6_10.x86_64/jre/bin/java -ea -javaagent:/usr/share/cassandra/lib/jamm-0.3.0.jar -XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=42 -Xms31744M -Xmx31744M -XX:+HeapDumpOnOutOfMemoryError -XX:+AlwaysPreTouch -XX:+UseTransparentHugePages -XX:HeapDumpPath=/tmp/cassandra-1616668789-pid7013.hprof -Xss256k -XX:StringTableSize=1000003 -XX:+ParallelRefProcEnabled -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:InitiatingHeapOccupancyPercent=25 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:+UseTLAB -XX:+ResizeTLAB -XX:-UseBiasedLocking -XX:+PerfDisableSharedMem -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime -XX:+PrintPromotionFailure -Xloggc:/var/log/cassandra/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=10M -Djava.net.preferIPv4Stack=true -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.password.file=/etc/cassandra/jmxremote.password -Djava.library.path=/usr/share/cassandra/lib/sigar-bin -Dcassandra.metricsReporterConfigFile=metrics-reporter-config.yaml -javaagent:/usr/share/java/jolokia-jvm-agent.jar=port=8080,host=sha8392 -Dlogback.configurationFile=logback.xml -Dcassandra.logdir=/var/log/cassandra -Dcassandra.storagedir= -Dcassandra-pidfile=/var/run/cassandra/cassandra.pid -cp /usr/share/java/metrics-core-3.1.2.jar:/usr/share/java/metrics-graphite-3.1.2.jar:/etc/cassandra/conf:/usr/share/cassandra/lib/ST4-4.0.8.jar:/usr/share/cassandra/lib/airline-0.6.jar:/usr/share/cassandra/lib/antlr-runtime-3.5.2.jar:/usr/share/cassandra/lib/cassandra-driver-core-2.2.0-rc2-SNAPSHOT-20150617-shaded.jar:/usr/share/cassandra/lib/commons-cli-1.1.jar:/usr/share/cassandra/lib/commons-codec-1.2.jar:/usr/share/cassandra/lib/commons-lang3-3.1.jar:/usr/share/cassandra/lib/commons-math3-3.2.jar:/usr/share/cassandra/lib/compress-lzf-0.8.4.jar:/usr/share/cassandra/lib/concurrentlinkedhashmap-lru-1.4.jar:/usr/share/cassandra/lib/crc32ex-0.1.1.jar:/usr/share/cassandra/lib/disruptor-3.0.1.jar:/usr/share/cassandra/lib/ecj-4.4.2.jar:/usr/share/cassandra/lib/guava-16.0.jar:/usr/share/cassandra/lib/high-scale-lib-1.0.6.jar:/usr/share/cassandra/lib/jackson-core-asl-1.9.2.jar:/usr/share/cassandra/lib/jackson-mapper-asl-1.9.2.jar:/usr/share/cassandra/lib/jamm-0.3.0.jar:/usr/share/cassandra/lib/javax.inject.jar:/usr/share/cassandra/lib/jbcrypt-0.3m.jar:/usr/share/cassandra/lib/jcl-over-slf4j-1.7.7.jar:/usr/share/cassandra/lib/jna-4.0.0.jar:/usr/share/cassandra/lib/joda-time-2.4.jar:/usr/share/cassandra/lib/json-simple-1.1.jar:/usr/share/cassandra/lib/libthrift-0.9.2.jar:/usr/share/cassandra/lib/log4j-over-slf4j-1.7.7.jar:/usr/share/cassandra/lib/logback-classic-1.1.3.jar:/usr/share/cassandra/lib/logback-core-1.1.3.jar:/usr/share/cassandra/lib/lz4-1.3.0.jar:/usr/share/cassandra/lib/metrics-core-3.1.0.jar:/usr/share/cassandra/lib/metrics-jvm-3.1.0.jar:/usr/share/cassandra/lib/metrics-logback-3.1.0.jar:/usr/share/cassandra/lib/netty-all-4.0.44.Final.jar:/usr/share/cassandra/lib/ohc-core-0.3.4.jar:/usr/share/cassandra/lib/ohc-core-j8-0.3.4.jar:/usr/share/cassandra/lib/reporter-config-base-3.0.0.jar:/usr/share/cassandra/lib/reporter-config3-3.0.0.jar:/usr/share/cassandra/lib/sigar-1.6.4.jar:/usr/share/cassandra/lib/slf4j-api-1.7.7.jar:/usr/share/cassandra/lib/snakeyaml-1.11.jar:/usr/share/cassandra/lib/snappy-java-1.1.1.7.jar:/usr/share/cassandra/lib/stream-2.5.2.jar:/usr/share/cassandra/lib/super-csv-2.1.0.jar:/usr/share/cassandra/lib/thrift-server-0.3.7.jar:/usr/share/cassandra/apache-cassandra-2.2.13.jar:/usr/share/cassandra/apache-cassandra-thrift-2.2.13.jar:/usr/share/cassandra/stress.jar: -Dcassandra.config=file:///etc/cassandra/conf/cassandra.yaml org.apache.cassandra.service.CassandraDaemon
422       7156  0.0  0.0   9256  1832 ?        S    10:39   0:00 bash -c (tail --pid 7131 -F /proc/7131/fd/0 | awk -v jre_pid=7131 -v jre_path='/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el6_10.x86_64/jre/bin/java' -f /usr/local/share/cassandra/parse_java8_gc_log.awk | logger -t java) &>/dev/null &
422       7158  0.0  0.0   9284  2028 ?        S    10:39   0:00 awk -v jre_pid=7131 -v jre_path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el6_10.x86_64/jre/bin/java -f /usr/local/share/cassandra/parse_java8_gc_log.awk```

**Comment by ReturnHttp402** [comment]
The issue seems to be related with using pssh and medusa to stop Casandra.
When ensuring everything is up and work, we try to stop Cassandra directly using pssh, it works for both ways:
``` pssh -H XXX -o stdout -e stderr "service cassandra start"```

```pssh -H XXX /etc/init.d/cassandra start```
and works for running medusa directly at the node

```medusa -vvv restore-node --in-place  --no-verify --backup-name 2021031803 --temp-dir /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc51```
although for this we got some info logs,
```[2021-03-25 10:58:21,412] INFO: Waiting for Cassandra to go down on 10.44.79.15
[2021-03-25 10:58:21,420] DEBUG: This server has systemd: False
[2021-03-25 10:58:21,420] WARNING: is ccm : 0
[2021-03-25 10:58:21,567] DEBUG: The node 10.44.79.15 is not up yet...
[2021-03-25 10:58:21,567] INFO: Cassandra is down 10.44.79.15
```

but it succeeded in the end.
but when combining together like restore cluster did, we get

``` tail -3 sha8392
[2021-03-25 11:04:15,582] DEBUG: Downloading /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc51/medusa-restore-7efb960b-cf00-4a6e-a467-3aa6a30e6942 as single part
[2021-03-25 11:04:15,635] DEBUG: https://s3.cn-north-1.amazonaws.com.cn:443 "GET /XXX/2021031803/meta/tokenmap.json?Version=2006-03-01 HTTP/1.1" 200 1535
[2021-03-25 11:04:15,636] INFO: Stopping Cassandra```
and 
```pssh -H XXX -o stdout -e stderr " medusa -vvv restore-node --in-place  --no-verify --backup-name 2021031803 --temp-dir /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc51"
[1] 11:04:36 [FAILURE] XXX Timed out, Killed by signal 9```

**Comment by Fredmomo** [comment]
> Hi @Fredmomo ! I know it's been a while. Did you manage to resolve this somehow in the end?

Hi @rzvoncek , I'm sorry I don't quite remember what's the final solution for this but it should be resolved in the end.

**Comment by rzvoncek** [comment]
Hello! Thanks a lot for comming back to us. And sorry for not getting to help you sooner. 
Since you say it's been resolved, I'll just close this one.
