### ISSUE TITLE
pssh forces 'sudo' for commands, make configurable?

### ISSUE THREAD

**Issue by mdesimone1** [thelastpickle/cassandra-medusa#318]
env: medusa 0.9.1, cassandra 3.11.5 running on Azure VMs, using azure container/blobs for storage

There are 2 (related) parts to my issue:

[1] when running backup-cluster, the ssh user in medusa.ini is the one that is running cassandra on the hosts, so we don't need to sudo to run nodetool. 

This line forces use of sudo: https://github.com/thelastpickle/cassandra-medusa/blob/30ed2e1561641434506a84d67fef6f2bb163b742/medusa/orchestration.py#L64

Can this be parameterized?

[2] By setting the sudo parameter to False, it did perform the remote nodetool command without sudo, but didn't pick up the environment, so reports this: **You must set the CASSANDRA_CONF and CLASSPATH vars**

Looking for a way to fix this so cluster-backup can work.  Single node backup works fine.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-212) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-212

**Comment by rhardouin** [comment]
Hi, 

1. I'm working on making Medusa work in Docker CI environment (with supervisord to use SSH) so I had to make sudo switchable, see [this branch](https://github.com/thelastpickle/cassandra-medusa/compare/master...teads:make_sudo_switchable). 
2. @mdesimone1 I've faced the same issue in my Docker container. I've just copy this file in `/etc/profile.d/cassandra_env.sh` as a workaround (adjust values as needed of course):
```
export PATH=/opt/cassandra/bin:/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export CASSANDRA_CONF=/etc/cassandra
export CASSANDRA_HOME=/opt/cassandra
export JAVA_HOME=/opt/java/openjdk
```

@adejanovski I can submit a PR if it's OK for you

**Comment by adejanovski** [comment]
@rhardouin, a PR would be greatly appreciated 🙂  Thanks!

**Comment by fronczek** [comment]
It's related to sudo behavior. For security reasons it clears PATH.
Our workaround (sudoers files):

```
Defaults:{{ medusa_backup_user }}  secure_path += ":/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin"

```

**Comment by rss04** [comment]
@mdesimone1 can you please help with configuration for medusa backup-cluster command over ssh. 
I was able to create SSH keys which works fine outside of medusa between ec2 instances but whenever I am running through medusa, I keep receiving keyimport error - https://github.com/thelastpickle/cassandra-medusa/issues/387
