### ISSUE TITLE
Bintray EoL 

### ISSUE THREAD

**Issue by idleyoungman** [thelastpickle/cassandra-medusa#330]
Looks like the scheduled brownout of Bintray ahead of its shutdown started today:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

The deb packages published there are currently unavailable.

**Comment by adejanovski** [comment]
Medusa's CI was just updated to publish deb packages to cloudsmith.io instead of Bintray: https://cloudsmith.io/~thelastpickle/repos/medusa/packages/
