### ISSUE TITLE
How to enable AWS encryption with KMS ?

### ISSUE THREAD

**Issue by mgrenonville** [thelastpickle/cassandra-medusa#338]
Hello, 

Thanks for this project !
I'm trying to enable encryption on S3 bucket, and it looks like it's possible since I've found this issue from jfharden on libcloud project https://github.com/apache/libcloud/issues/1401

Is there a mini-how to to help me in this task ?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-197) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-197

**Comment by adejanovski** [comment]
While libcloud allows this, we don't seem to support it in Medusa.
We already have a [similar flag](https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa-example.ini#L126) to disable md5 checks, which could be used to set `verify_hash=False` on S3 uploads [here](https://github.com/thelastpickle/cassandra-medusa/blob/3c01bef73bf266f84c6c7357b07c72a8a5386b86/medusa/storage/s3_compat_storage/concurrent.py#L133-L135).

We happily accept PRs ;)

**Comment by justinmir** [comment]
I've taken a stab at an implementation for KMS support in Medusa. I can iterate on the implementation or look at alternative approaches if another is more ergonomic.
