### ISSUE TITLE
Set nodetool parameters

### ISSUE THREAD

**Issue by bhagenbourger** [thelastpickle/cassandra-medusa#34]
We need to set nodetool parameters like a password or a port. I suggest to add a nodetool section into the medusa.ini config file and use parameters defined into this section to build nodetool commands.
The nodetool section could have these parameters, only set parameters will be used including:
 - username
 - password
 - passwordFilePath
 - host
 - port

**Comment by arodrime** [comment]
Sounds good to me. Yet we are using rather '_' than CamelCase. Also there is a section called `cassandra` with some cql_* configs, thus it would make sense to me to add up to this existing section:

To be clear, I think the [medusa-example.ini](https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa-example.ini#L15-L20) could look like this:
```
[cassandra]
;stop_cmd = /etc/init.d/cassandra stop
;start_cmd = /etc/init.d/cassandra start
;config_file = <path to cassandra.yaml. Defaults to /etc/cassandra/cassandra.yaml>
;cql_username = <my_cql_username>
;cql_password = <my_cql_password>
;nodetool_username =  <my_nodetool_username>
;nodetool_ password =  <my_nodetool_ password>
;password_file_path = <path to nodetool password file>
;nodetool_host = <host name or IP to use for nodetool>
;nodetool_port = <port number to use for nodetool>
```

**Comment by arodrime** [comment]
This was merged. Closing the issue.

Thanks @bhagenbourger, sorry about the delay (around Christmas it is a bit of a tricky period).
