### ISSUE TITLE
Trigger medusa from a dedicated non-cassandra server

### ISSUE THREAD

**Issue by optplx** [thelastpickle/cassandra-medusa#347]
Hello,

for security reason, we would like to trigger medusa from a dedicated, non-cassandra server and not from one of the node of the cluster. The main purpose is to not have the cassandra nodes ssh each other and to let the external server handle this.
Though when we launch medusa, it complains saying that it can't find the cassandra.yaml  file (which is normal since the server launching the command is not a Cassandra server).

* Is this possible to do with the current medusa code?
* If not, is there a specific reason for this? Or could we cooperate via a PR to make this option available?

Thanks for your help :)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-194) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-194

**Comment by adejanovski** [comment]
We could probably implement both cleanly so that jump hosts are fully supported.
We need to bypass anything that looks for stuff locally (we can silently skip reading cassandra.yaml in the restore-cluster operation) and add the `--seed-target` arg to `backup-cluster` with the wiring to make it work seamlessly from a cassandra node or a jump host.

**Comment by optplx** [comment]
Thanks for the feedback @adejanovski  :) that would be great, I will have a look at this in the coming days

**Comment by adejanovski** [comment]
Your help is very much appreciated @optplx!

Thanks for the efforts you're putting improving Medusa 🙏

**Comment by optplx** [comment]
My pleasure @adejanovski , happy to contribute :) I have just pushed a first PR about this issue. 

I am not sure yet how to silently skip reading cassandra.yaml in the restore-cluster operation yet though, the exception raised is [this one](https://github.com/thelastpickle/cassandra-medusa/blob/9bd31e377a762e01fcf8664fa9691b48196ee36e/medusa/cassandra_utils.py#L210) but I need to figure out how to identify that we are in a restore-cluster step

I'll probably have a look next week but if you have any pointer about it that could definitely help

**Comment by optplx** [comment]
closing this issue even if only half of it is fixed, I won't have time in the coming days to handle the rest of it as the workaround seems easy enough  (have a `foo:bar` yaml file instead of real `cassandra.yaml` file on the medusa "controller" server)
