### ISSUE TITLE
Race conditioin during purge causes silent backup corruption

### ISSUE THREAD

**Issue by spintower** [thelastpickle/cassandra-medusa#363]
When a backup and a backup purge happen to run at the same time, the purge might delete files that are being uploaded by the backup, causing **silent and permanent data loss**. 

The backup process uploads the blobs first, and then creates the manifest pointing to these blobs. 

The purge process looks at all existing manifests and then deletes all blobs that are not referenced in any of the manifests ("orphaned blobs").

If the purge process happens to run **after** a new blob has been uploaded but **before** the manifest referencing the new blob has been created, the purge process will consider the newly uploaded blob "orphan" and delete it from storage. Essentially, all new blobs uploaded during a backup are not referenced by any manifest until the backup is complete - so they are "orphan" blobs that should be deleted.

This will cause the backup that includes the now-deleted blob to become corrupt. No warning or error messages will be produced. All later backups will read the current backup's manifest and assume that the blob referenced by the manifest exists in the storage and will not attempt to re-upload it. This will cause all consequent differential backups to be corrupt as well. 

It's possible that in the initial design there was never an intention to run backup and purge at the same time, but in places where backups are managed by multiple human and automated actors I can see this happen very easily. The biggest problem is, this only needs to happen once for multiple backups to become silently corrupted, and there is no way to determine if this happened except periodically verifying all backups. This is the worst possible state for a backup - the user thinks that they have a backup, but in reality they don't.

There are 2 ways to fix it that I see:

1. Since the list of files to be uploaded is known at the start of a backup, the manifest with the names of new blobs can be created and uploaded at the start of the backup. This will create references to the expected blobs and prevent their deletion by purse process. The manifest would have to be re-uploaded once all MD5s are calculated.
1. Verify presence of blobs that the new backup is going to "inherit" from the old ones instead of assuming that they are all present. If a blob referenced by a previous backup's manifest is missing and we have a local copy of the file with the same MD5 as listed in the manifest, just upload it again. This will patch the previous backups and make them whole again as well as preventing the current backup from becoming corrupted.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-564) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-564
┆Priority: Medium

**Comment by adejanovski** [comment]
Thanks for reporting this issue. It's a bad one indeed.
We've been discussing it on the ASF Slack and a simpler way to fix this issue would be to define a gc grace period for backup files, preventing their purge until they reached at least 1 day of age. That should solve all race conditions cases (unless backup takes more than a day, which would be very long...).

wdyt?

**Comment by spintower** [comment]
Considering how many things can wrong with time (https://gist.github.com/timvisee/fcda9bbdff88d45cc9061606b4b923ca) this solution is a ticking time bomb. It's based on an assumption that a blob will never become more than 24 hours old before the manifest is uploaded. For my Cassandra backups I need a guarantee, not an assumption. If this solution is implemented, the docs would need to include a warning that silent and unrecoverable data loss is possible if a backup happens to run longer than 24 hours (or whatever the gc grace period is).

**Comment by adejanovski** [comment]
Fair enough, then we could tie the success of a backup to its duration compared to the gc grace value. Backups that took more than the gc grace period would be marked as failed and would not be used to build the next differential backup.
And I'm saying one day, but we could use a default of 10 days which would be similar to tombstone's gc grace. If the purge is conditioned by a max age, that value could also be used to override gc grace.
While I reckon time is not fully reliable, it's used widely for such mechanisms (see Cassandra) and we can build something that will ensure enough safety.

> Since the list of files to be uploaded is known at the start of a backup, the manifest with the names of new blobs can be created and uploaded at the start of the backup. This will create references to the expected blobs and prevent their deletion by purse process. The manifest would have to be re-uploaded once all MD5s are calculated.

That would be hard to do with the current implementation as the manifest is built during the upload process. We'd need quite a lot of changes to make that happen.

> Verify presence of blobs that the new backup is going to "inherit" from the old ones instead of assuming that they are all present. If a blob referenced by a previous backup's manifest is missing and we have a local copy of the file with the same MD5 as listed in the manifest, just upload it again. This will patch the previous backups and make them whole again as well as preventing the current backup from becoming corrupted.

This is a good suggestion. While the manifest is nice to have, we'd need to double check that the files are indeed present in the backup data folder so that differentials won't be broken until missing/corrupt sstables are compacted away in the source node. I'll create a separate issue for this.

**Comment by spintower** [comment]
Thank you for a quick fix. Unfortunately, I see some downsides of this approach. They are all related to the presence of invisible and unmanageable orphan blobs that this approach allows in the storage account.

1. There is no way for me to see orphaned blobs that are left in the storage after purge. 
2. There is no way in medusa to force removal of orphan blobs before the end of GC period.
3. If I create a backup and immediately purge it, most of the backed up blobs will likely stay in the storage instead of being correctly deleted.
4. I can never be sure that all data is deleted from the storage account even if all backups are completely purged.

This approach fixes the corruption problem, which is great, but it also introduces a data "leak" which can put users in jeopardy if they have legal or contractual obligations to completely delete backed up data.

**Comment by adejanovski** [comment]
This can be improved by providing more feedback at the end of the purge and a `--gc-period` flag for the purge operation which would allow to override the value.

I wouldn't consider this a leak, but agree that more clarity would be beneficial.
