### ISSUE TITLE
Check actual file presence when performing differential backups

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-medusa#368]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13938589)

Follow up to #363 

Verify presence of blobs that the new backup is going to "inherit" from the old ones instead of assuming that they are all present. If a blob referenced by a previous backup's manifest is missing and we have a local copy of the file with the same MD5 as listed in the manifest, just upload it again. This will patch the previous backups and make them whole again as well as preventing the current backup from becoming corrupted.

This prevents a corrupted backup from breaking all subsequent backups.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1403) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1403
┆priority: Medium

**Comment by rzvoncek** [comment]
Relates to #716 .
