### ISSUE TITLE
medusa backup-cluster failing with keyimporterror

### ISSUE THREAD

**Issue by rss04** [thelastpickle/cassandra-medusa#387]
Hi,
I have configured medusa.ini with SSH info as follows:

[ssh]
username = cassandra
key_file = /etc/cassandra/conf/certs/ssh-cassandra-medusa.key.pem
port  = 22
cert_file = /etc/cassandra/conf/certs/ssh-cassandra-medusa.pub.pem

On executing the following command, 
**medusa -v backup-cluster --backup-name=yq-test-backup --mode=full**

I am receiving the following error:

DEBUG: _run_command with read timeout None
[2021-07-18 12:57:11,195] DEBUG: Make client request for host ip-172-18-76-200.ec2.internal, (host_i, host) in clients: False
[2021-07-18 12:57:11,195] DEBUG: Connecting to ip-172-18-76-200.ec2.internal:22
[2021-07-18 12:57:11,200] DEBUG: Starting new session for cassandra@ip-172-18-76-200.ec2.internal:22
[2021-07-18 12:57:11,200] DEBUG: Session started, connecting with existing socket
[2021-07-18 12:57:11,220] DEBUG: Proceeding with private key file authentication
[2021-07-18 12:57:16,222] DEBUG: Proceeding with private key file authentication
[2021-07-18 12:57:21,227] DEBUG: Proceeding with private key file authentication
[2021-07-18 12:57:21,227] ERROR: Failed to run on host None - ('Authentication error while connecting to %s:%s - %s', 'ip-172-18-76-200.ec2.internal', 22, KeyImportError())
[2021-07-18 12:57:21,233] ERROR: This error happened during the cluster backup: ('Authentication error while connecting to %s:%s - %s', 'ip-172-18-76-200.ec2.internal', 22, KeyImportError())
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pssh/clients/base/single.py", line 97, in _auth_retry
    self.auth()
  File "/usr/local/lib/python3.7/site-packages/pssh/clients/ssh/single.py", line 168, in auth
    return self._pkey_auth(self.pkey, self.password)
  File "/usr/local/lib/python3.7/site-packages/pssh/clients/ssh/single.py", line 207, in _pkey_auth
    pkey = import_privkey_file(pkey, passphrase=password if password is not None else '')
  File "ssh/key.pyx", line 172, in ssh.key.import_privkey_file
ssh.exceptions.KeyImportError

I am able to connect to the instances using ssh over command line without any issues.
**I have not set any passphrase for keys.**
Can anyone please advise what exactly is the error ? 
Is it anything related **pssh client** ? 

Thanks,
Srivats

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1401) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1401
┆priority: Medium

**Comment by m934030039** [comment]
rss04,

>Is it anything related pssh client ?
The deault setting of pssh is working to me test-bed with enabling encryption.

    I assumed the key pair is good in this case.

    3 things to check.
    #1. .cqlshrc file has to add sections related to encryption parts e.g. [authentication] and [ssl]
    #2. In my test-bed, medusa.ini required certfile, userkey and usercert.
    #3. cassandra.yaml to enable encryption.

-Sheng

**Comment by m934030039** [comment]
Hi rss04,

    I just saw this message here.
    I thought Github will send the the email for this.

   Were you trying to do the medusa  backup with encryptions?
   I focused on  #2. In my test-bed, medusa.ini required certfile, userkey and usercert.
   We put "certfile, userkey and usercert" in [cassandra] section NOT [ssh] section.
    
   Hopefuly, it can help.

-Sheng

**Comment by adejanovski** [comment]
@rss04, I think the expected cert file isn't the public part of your ssh key. You should actually try to remove the `cert_file` entry in `medusa.ini` and just set `username` and `key_file` to see how it goes.

When you connect through ssh using this key, does the command look like the following? `ssh -i /etc/cassandra/conf/certs/ssh-cassandra-medusa.key.pem cassandra@ip-172-18-76-200.ec2.internal` 
If so, I guess it should work fine after removing the cert file 🤞

**Comment by adejanovski** [comment]
Hi @rss04, are you still experiencing this issue?

**Comment by jsanda** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/thelastpickle/cassandra-medusa/387?planning-poker) with ZenHub @adejanovski

**Comment by adejanovski** [comment]
@jsanda, I'm going to close this ticket as this looks more like a configuration problem.
@rss04, feel free to reopen it if you're still having this issue..

**Comment by jralmaraz** [comment]
Just a note here: I have faced the same issue when running a `restore-cluster` and commenting out the `cert_file` did help. Thanks for that @adejanovski .

Maybe the documentation should be a bit more clear on why that `cert_file` is needed and if its only for signed SSH keys, for example ?

Thanks!

**Comment by m934030039** [comment]
Hi,

  Here is my feedback from my perspective.

  Do we have someone who is a Linux System Admin. background in this team ?

  If so, I suggest adding the main general purpose of the entry for Medusa
operation in the medusa.ini file.

  In this way, users can know more about how Medusa operates and developers
can focus on real issues.

  Maybe those general purposes are put on the documents but sometimes
people will NOT read those Info. (different backgrounds)

  And it takes time and a lot of effort. (both users and authors)

*  But in general, the medusa-example.ini file is good for me.*

  e.g.
      I will explain why we need to add an ssh key because restoring
required ssh passwordless login.
      I will explain why we need to add a Cert. file because C* nodes
enabled encryption to protect data integrity.

- Sheng
