### ISSUE TITLE
Backup method in gRPC service does not support full backups

### ISSUE THREAD

**Issue by jsanda** [thelastpickle/cassandra-medusa#389]
The backup type is hard coded to `differential` in `server.py`. The request for this change originated from https://github.com/k8ssandra/k8ssandra/issues/1024. We already have a PR with the necessary changes in medusa-operator, https://github.com/k8ssandra/medusa-operator/pull/60.

**Comment by adejanovski** [comment]
This was handled already and the grpc server now supports both modes.
