### ISSUE TITLE
Is the Medusa version required the same around the nodes when doing differential backups?

### ISSUE THREAD

**Issue by m934030039** [thelastpickle/cassandra-medusa#404]
Can someone confirm that the differential backups fail with different version of Medusa (e.g. 0.9.1 and 0.10.1)? 

Here is our obeservation that some of nodes with version 0.9.1 and some of nodes with 0.10.1 in the same cluster.

#1. To do full backup with S3 is no problem.

#2. It failed when doing differential backups with S3 until all nodes with the same version 0.10.1

In the medusa release note, there is no fixs for differential backup in for 0.9.1 and 0.10.1 
https://github.com/thelastpickle/cassandra-medusa/blob/master/CHANGELOG.md

Logically, all nodes with the same Medusa version are better.

-Sheng

**Comment by adejanovski** [comment]
Hi @m934030039,

we do not perform any testing with mixed versions of Medusa, which leaves the door open to failure when taking backups in this situation.
I'd strongly recommend to perform backups only when all Medusa versions are the same indeed.

**Comment by m934030039** [comment]
Hi Alex,

     Thx for your confirmation.
     
  
-Sheng
