### ISSUE TITLE
Can diff. and full backups methods co-exist ?

### ISSUE THREAD

**Issue by m934030039** [thelastpickle/cassandra-medusa#405]
Hi guys,

Goal: We want to be able to run full backup once a week and differential on all the other days.  

We have 40 nodes and each node contains 2.6 TB cassandra data.

In the past, we did full backup method was perfectly well.

Now, we mixed full and differtetial backup methods together but the backup sometimes complete successfuly and sometimes incomplete.

Here is the commands below
# cstar run --command="medusa backup --backup-name=s3.full_$(date +%Y%m%d) --mode=full" --seed-host=1.2.3.4 --strategy=all >> $getBackupLog 2>&1

# cstar run --command="medusa backup --backup-name=s3.diff_$(date +%Y%m%d) --mode=differential" --seed-host=1.2.3.4 --strategy=all >> $getBackupLog 2>&1

[~]$ medusa list-backups
s3.full_20210829 (started: 2021-08-29 20:00:08, finished: 2021-08-30 01:16:13)
s3.diff_20210904 (started: 2021-09-04 02:40:09, finished: 2021-09-04 08:09:33)
s3.full_20210905 (started: 2021-09-05 20:00:08, finished: Incomplete [36 of 40 nodes finished])
s3.diff_20210906 (started: 2021-09-06 20:00:09, finished: 2021-09-07 01:17:52)
s3.diff_20210907 (started: 2021-09-07 20:00:09, finished: 2021-09-07 22:09:39)
s3.full_20210907 (started: 2021-09-07 22:17:07, finished: Incomplete [38 of 40 nodes finished])
s3.diff_20210908 (started: 2021-09-08 20:00:09, finished: Incomplete [39 of 40 nodes finished])
s3.diff_20210909 (started: 2021-09-09 20:00:08, finished: 2021-09-10 01:35:19)
s3.diff_20210910 (started: 2021-09-10 20:00:08, finished: 2021-09-10 20:44:57)
s3.diff_20210911 (started: 2021-09-11 20:00:09, finished: 2021-09-11 20:27:23)
s3.full_20210912 (started: 2021-09-12 20:00:07, finished: 2021-09-15 05:57:43)
s3.diff_20210913 (started: 2021-09-13 20:00:09, finished: Incomplete [39 of 40 nodes finished])
s3.diff_20210914 (started: 2021-09-14 20:00:07, finished: 2021-09-15 08:23:27)

-Sheng

**Comment by m934030039** [comment]
Have anyone tried mix backup stargeties this before?

More importantly, does Medusa can support the mix backup stargeties, together ?

Many thanks,

-Sheng

**Comment by adejanovski** [comment]
Hi @m934030039,

You should be able to perform mixed backups without a problem. Differential backups should be lighter so I see no valid reason why you would have unfinished backups in differential mode that you wouldn't have in full.
You should check the logs under `/tmp/medusa-job-******/stderr` on the nodes that failed the backup to see why it failed.

**Comment by m934030039** [comment]
Alexander,

     We will look up the error log uner /tmp.

     In the past experience, we based the example of medusa.ini file to increase the transfer rate and concurrent upload would resolve full backup incompleted issue.

    But, this approach seems not work this time.

    My observation that huge data (2.6 TB x 50 nodes) for backup to S3 requires huge network bandwidth and more concurrent upload threads otherwise it will fail.

   Does that make sense to Medusa?  I am not sure if it is an issue to Medusa.

   My suggestion is that Medusa would indicate the required transfer rate or concurrently upload thread based on the backup data  size  to  make sure the backup completed successfully.

-Sheng

**Comment by m934030039** [comment]
Hi Alexander,

     In this case, mixed backup stargeties, the backup result turned out "Failed to find uploaded object".

     Can we conclude the below error message is not caused by Medusa or Cassandra?

ERROR: This error happened during the backup: Failed to find uploaded object test-cluster-01/cass-01.example.org/s3.medusa-test/data/prd/device/md-20059-big-Data.db in S3


      Can I make a general assumption below ?   
      Medusa will check the return value of uploaded data from S3.
      If Medusa did not get the return value, Medusa will raise the above error message.

-Sheng

**Comment by spintower** [comment]
We use both full and differential backups with the same cluster and storage container and see no issues from mixing them.

**Comment by m934030039** [comment]
Hi spintower,

    If you can provide more Info. that will help.

     What is your ENV? such as cloud platform and so on ?
     What storage you are using ?
     What command you are using ?
     What is the data szie of eacho node ?
     What is your Medusa.ini like?

-Sheng

**Comment by adejanovski** [comment]
They don't. Full and Differential backups use distinct storage locations.

IMO full backups have no value over differential and will soon be deprecated and removed.

**Comment by alokhom** [comment]
@spintower 
What is the meaning of differential file in a medusa full backup. Does a full backup use differential way ?
![image](https://user-images.githubusercontent.com/12021776/154699921-07baa7f1-ff87-4561-9a96-5c18a6d4645f.png)
```    
apiVersion: cassandra.k8ssandra.io/v1alpha1
kind: CassandraBackup
metadata:
     name: medusa-fullbackup-timestamp
     namespace: cassandra
spec:
    backupType: "full"
    name: "medusa-fullbackup-timestamp"
    cassandraDatacenter: "dc1"
```
I am using this script.

**Comment by alokhom** [comment]
@spintower  do you also plan to use restic inside medusa ?

**Comment by adejanovski** [comment]
I'll close this ticket as the original question was answered.
