### ISSUE TITLE
Restore python script in k8s entry point script should not be invoked with exec

### ISSUE THREAD

**Issue by jsanda** [thelastpickle/cassandra-medusa#408]
See https://github.com/k8ssandra/k8ssandra/issues/1112 for detailed description of the bug. The entry point script for the k8s Docker file used in k8ssandra has the following:

```bash
echo "Restoring backup $BACKUP_NAME"
exec python3 -m medusa.service.grpc.restore
echo $RESTORE_KEY > $last_restore_file
```
The script checks `last_restore_file` to determine whether or not it should perform a restore operation. With `exec` no subshell is created which means the container exits after the Python script finishes. Thus, `last_restore_file` is never created/updated.

**Comment by adejanovski** [comment]
Fix released in 0.11.3
