### ISSUE TITLE
Backing up to Google Cloud Storage results in broken backups

### ISSUE THREAD

**Issue by elsmorian** [thelastpickle/cassandra-medusa#414]
When just trying to get to grips with medusa and how it works, I'm trying to do a trial backup and restore.

The cassandra cluster is a single node with one created keyspace and table:
```CREATE KEYSPACE "2021_10_14_test_keyspace" WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE "2021_10_14_test_keyspace".my_test_table (
    id int PRIMARY KEY,
    name text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```
With a few bits of test data in.

Backing up this seems to complete fine and the backup gets pushed to GCS, however verification fails with the following error:
https://gist.github.com/elsmorian/5431a3abc4644cdb60cfbe46c899105a

Trying to restore this backup to the cluster results in a very broken experience which is not really surprising:
https://gist.github.com/elsmorian/7026199d154035ec4327f68b8707be02

I have confirmed that this seems to be a bug in the GCS driver, as I have attempted a backup and restore using the local driver with the same cluster and versions and that all worked with no problems.

Versions:
```
Medusa: 0.11.1
Cassandra: 2.2.19
GCS storage
Ubuntu Focal 20.04
```

**Comment by elsmorian** [comment]
Turns out this seems to be an edge case with our single node cluster set up - setting up GCS on a real cluster did not suffer these same issues.

**Comment by elsmorian** [comment]
We are still seeing this issue on a production cluster unfortunately. We have narrowed it down to the following:

We are using `medusa --verbosity backup-node --backup-name $(date --iso-8601=hours) --mode differential  --enable-md5-checks`  The first initial backup completes fine, verifies ok and is restorable no problem. However subsequent runs of that command to create further backups complete, but dddo not verify with the same kind of errors as mentioned above.

**Comment by adejanovski** [comment]
@jdonenine, we'd need to investigate this issue, it's a little concerning that Medusa is creating broken backups in GCS 😕

**Comment by elsmorian** [comment]
I'm currently running a differential backup to see if that succeeds to try and narrow it down further, very happy to try and help debug if I can be of use!

**Comment by elsmorian** [comment]
After debugging further I can confirm when running differential backups they complete successfully and verify no problem, but full mode backups break

**Comment by adejanovski** [comment]
I'll close the issue @elsmorian as we're planning to remove support for full backups soon.
