### ISSUE TITLE
NetApp Storage Grid Query Parameter Issue

### ISSUE THREAD

**Issue by mikelitka** [thelastpickle/cassandra-medusa#426]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952035)

Version: 0.11.2
Storage Provider: s3_compatible
Object Storage: NetApp StorageGrid

We are trying to backup to an S3 compatible NetApp StorageGrid. This seems to fine until the tokenmap is downloaded for what I assume is a verification operation. We get a 501 back complaining about an invalid query parameter ?Version=2006-03-01.

However, in the libcloud debug logs, I don't see a request being sent with this query parameter.

Does anyone have any insights they could share here? 

Please see attached log file.

[libdebug.log](https://github.com/thelastpickle/cassandra-medusa/files/7571390/libdebug.log)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1395) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1395
┆priority: Medium

**Comment by mikelitka** [comment]
I setup a man in the middle proxy to analyze this traffic. It appears that we are sending a ?Version query parameter on GET requests.

This fixes the issue:

In:

libcloud/common/aws.py

Commenting out the Version parameter logic fixes the 501 response from the NetApp StorageGrid

class AWSRequestSignerAlgorithmV4(AWSRequestSigner):
    def get_request_params(self, params, method='GET', path='/'):
        return params
        #if method == 'GET':
        #    params['Version'] = self.version
        #return params

Not knowing this codebase well, would this be fixable using a new storage provider?

I also have a ticket open with NetApp to advise on why they don't like this behavior.

**Comment by rzvoncek** [comment]
We moved away from libcloud meanwhile.
