### ISSUE TITLE
detail step by step installation about cassandra-medusa tool

### ISSUE THREAD

**Issue by nedretsolmaz** [thelastpickle/cassandra-medusa#43]
Hi there

i am looking for detail step by step installation about cassandra-medusa tool?

your setup page is not enough, i got many issues about that..

for example there is no any mentioning about requirements before installation..

please someone can help me about details, step by step installation for this beauty tool..

Thanks

Ned

**Comment by nicholasamorim** [comment]
- `pip install cassandra-medusa` is all you need.
- You need at least python3.5
- the last version that updates recent fixes have not been released yet, so use , `pip install https://github.com/thelastpickle/cassandra-medusa/archive/master.zip`

Other than that, you need `/etc/medusa/medusa.ini` and `/etc/medusa/credentials` in case you're using credentials.

**Comment by nedretsolmaz** [comment]
Hi Nicholas,

So first step is to install Python3.5 or over 3.5
Then the second step is just running the command below..

pip install cassandra-medusa-master

Or

pip install cassandra-medusa

Which one??

And moreover do I have to unzip this file before running one of the
above command?

And after that I need to create medusa.ini file under /etc/Medusa
directory. Correct?

Please guide me, because I am not a system administrator, am a Dba..

And in my 3 node cluster there is no any  internet connection, they are
redhat Linux x86_64 7.6

Thanks

Ned

**Comment by nicholasamorim** [comment]
If you run `pip install cassandra-medusa` it will install _released_ versions which are usually stable.

If you run `pip install https://github.com/thelastpickle/cassandra-medusa/archive/master.zip` - it will install the **master** branch of this repo.


> And after that I need to create medusa.ini file under /etc/Medusa
directory. Correct?

yes

**Comment by nedretsolmaz** [comment]
Hi again Nicholas,

But as I said before, I don't have internet connection for these Linux
servers..

So I had to download cassandra-medusa from the github page.

But it is like that

cassandra-medusa-master

And the other one is
cassandra-medusa.3.0.1
something like that..

So I have to run the command like that
pip install cassandra-medusa-master
Or
pip install cassandra-medusa.3.0.1

Which one?

There is no detail guide about that.. :((

Ned

**Comment by nicholasamorim** [comment]
A detailed guide about installing python packages without internet connections is outside the scope of... well, the readme of any python project.

You won't be able to easily download 1 package and install it as it has several requirements. I suggest googling "installing python packages without internet" and similars.

**Comment by nedretsolmaz** [comment]
Hi Nicholas,

Finally I have installed Python3.6 on my servers..

But again when I run the command
pip3 install cassandra-medusa

It is not installed because I have no internet connection in this
environment..

It requires downloading some packages from pythonhosted.org side..

Is there any other option to install without internet connection for
cassandra-medusa tool..

Thank you very much

I really want to try/test this beauty tool..


Ned

**Comment by nedretsolmaz** [comment]
Hi Nicholas,

Finally I have installed Python3.6 on my servers..

But again when I run the command
pip3 install cassandra-medusa

It is not installed because I have no internet connection in this
environment..

It requires downloading some packages from pythonhosted.org side..

Is there any other option to install without internet connection for
cassandra-medusa tool..

Thank you very much

I really want to try/test this beauty tool..


Ned

**Comment by docent-net** [comment]
@nedretsolmaz `pip` allows you to download packages (from a machine where you have internet access) and later on install it without internet connection (assuming you somehow copied those files to this machine).

simply run: `pip download cassandra-medusa` from a machine where you have internet access

(on older pip versions you may need to use `pip install --download cassandra-medusa`

now copy somehow downloaded files to the destination machine where you want cassandra-medusa installed

lastly run `pip install --no-index --find-links /path/where/you/uploaded/files` on the destination machine

you may need to add `--no-deps` to the last command (not sure)

also make sure that pip versions are exactly same on both machines; otherwise, it may not work

**Comment by nedretsolmaz** [comment]
No no I said that I have no internet connection so that I want to find out
how can I install it, I don't know which packages it needs

**Comment by nedretsolmaz** [comment]
Is there any other option to install without internet connection for
cassandra-medusa tool..

It requires downloading some packages from pythonhosted.org side..

Can you send me which packages they are so that I can install like you
said.

Thank you very much

**Comment by nicholasamorim** [comment]
I think every possible instruction has been given... Anyways, here's my last bit:

```
apache-libcloud==2.7.0
bcrypt==3.1.7
cassandra-driver==3.20.2
cassandra-medusa==0.3.1
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
cryptography==2.8
enum34==1.1.6
ffwd==0.0.2
gevent==1.4.0
greenlet==0.4.15
idna==2.8
lockfile==0.12.2
parallel-ssh==1.9.1
paramiko==2.7.1
psutil==5.6.7
pycparser==2.19
pycrypto==2.6.1
PyNaCl==1.3.0
python-dateutil==2.8.0
PyYAML==5.2
requests==2.22.0
retrying==1.3.3
six==1.13.0
ssh2-python==0.18.0.post1
typing==3.7.4.1
urllib3==1.25.7
```

**Comment by nedretsolmaz** [comment]
Thank you I will try this ones..

To be clear I wanna say that

I downloaded cassandra-medusa.0.3.1

But when I run
pip3 install cassandra-medusa

It tries to download other packages from pythonhosted.org side..
And I have no internet connection in this environment.
That's why I asked which packages they are..

If they are the ones you mentioned previous mail then I can install..

Hope to write detail Installation in your blogs for no internet connection
case

Thanks

**Comment by adejanovski** [comment]
The simplest way to install a python app with all its dependencies, on a server with no internet access, is through debian or rpm packages.
We're close to have debian packages available but don't have an immediate solution for rpm packages.

You can still download the dependencies on a machine that has the same os and version of python, compress them and install them offline on the target servers as described [here](https://stackoverflow.com/a/51646354/5106246).
In a nutshell:
- clone the cassandra-medusa repo and cd into the root directory
- run `mkdir pip_dependencies && pip download -r requirements.txt -d pip_dependencies` to download the dependencies into a sub directory
- run `cp requirements.txt pip_dependencies/`
- run `tar -zcf medusa_dependencies.tar.gz pip_dependencies` to compress the dependencies
- Upload the archive to all Cassandra nodes and decompress it
- run `pip install -r medusa_dependencies/requirements.txt --no-index --find-links` to install the dependencies on the nodes
- install Medusa using `python setup.py install` from the cassandra-medusa source directory

**Comment by nedretsolmaz** [comment]
Hi Alexander,

I will try within a few days, then let you know..

Thank you

**Comment by adejanovski** [comment]
I've written down more precise instructions in the wiki : https://github.com/thelastpickle/cassandra-medusa/wiki/Installation
