### ISSUE TITLE
hide imdsv2 INFO message

### ISSUE THREAD

**Issue by Anasme** [thelastpickle/cassandra-medusa#432]
Hello, a quick question, I would like to not display the "info" message related to imdsv2, not being on EC2 but using S3 to store our backups.

Is this possible?

example:
```
$ medusa status --backup-name test
[2021-12-29 10:20:51,263] INFO: Could not use imdsv2: got an exception while reaching http://169.254.169.254/latest/api/token: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fe1e0c416a0>, 'Connection to 169.254.169.254 timed out. (connect timeout=2)'))
test
- Started: 2021-12-29 10:15:40, Finished: 2021-12-29 10:17:01
- 3 nodes completed, 0 nodes incomplete, 0 nodes missing
- 872 files, 1.63 MB
```

Thanks in advance for your help.

**Comment by Anasme** [comment]
At the moment I'm redirecting the error so that it doesn't show up on my backup reports, the question is more whether it's the desired behavior that 'imdsv2' is requested by default without having the choice to enable it or not.

Sorry I don't know imdsv2, what I understand is that it is only useful if the medusa service is under EC2 instance?

Thanks to you.

**Comment by adejanovski** [comment]
Hi @Anasme,

using imdsv2 isn't required indeed and is only useful when running on EC2 instances. It allows to use the instance role for access rights instead of passing credentials.
We could probably move this logging to DEBUG instead of INFO since it's not always relevant.

**Comment by Anasme** [comment]
Hi @adejanovski,
Thank you for your answer and for the information you provided. 

+1 for the debug mode :).
