### ISSUE TITLE
Investigate usage of DockerSlim to reduce the Medusa image sizes

### ISSUE THREAD

**Issue by adutra** [thelastpickle/cassandra-medusa#434]
DockerSlim claims to be able to reduce image sizes drastically:

https://developers.redhat.com/articles/2022/01/17/reduce-size-container-images-dockerslim

We could investigate using DockerSlim to reduce the Medusa image sizes – these have grown bigger lately with the addition of Azure support.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1392) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1392
┆priority: Medium

**Comment by jsanda** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/thelastpickle/cassandra-medusa/434?planning-poker) with ZenHub @adejanovski
