### ISSUE TITLE
Authentication problems after using restore-cluster

### ISSUE THREAD

**Issue by baileygm** [thelastpickle/cassandra-medusa#437]
I am using medusa version 0.10.1 and trying to restore a single keyspace from a backup taken from another cluster to a 3 node test cluster

Before restoring the keyspace I check the system_auth keyspace has a Replication factor of 3

> select system_auth from system_schema.keyspaces;
 keyspace_name      | durable_writes | replication
--------------------+----------------+------------------------------------------------------------------------------
system_auth |           True | {'DataAnalytics': '3', 'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy'}

Using the command "medusa restore-cluster --backup-name=2022-02-03-03 --keep-auth --keyspace=test"
the keyspace is restored and the cassandra nodes started however they repeatedly give a warning "CassandraRoleManager skipped default role setup: some nodes were not ready"

I notice that I am unable to authenticate to cqlsh and by trying to repair system_auth I can see that the replication has been reset to 1

> nodetool repair system_auth
[2022-02-03 10:28:55,515] Replication factor is 1. No repair is needed for keyspace 'system_auth'

Is this a known issue or am I using the restore-cluster command incorrectly ?

**Comment by adejanovski** [comment]
Hi @baileygm,

the cluster on which the backup was taken has 3 nodes as well?
Note that `--keep-auth` won't touch the `system_auth` keyspace sstables, but the `system_schema` keyspace will get recreated whatever happens. So if the original cluster system_auth replication strategy is set to RF1, then it will be the same on the restore cluster.

**Comment by baileygm** [comment]
The original cluster on which the backup was taken had 3 DC's each with 3 nodes
The replication for system_auth was set to NetworkTopology: 3 in each DC

**Comment by adejanovski** [comment]
Did the restore cluster use the same dc name as the original cluster? Seems to be `DataAnalytics` here.

**Comment by baileygm** [comment]
In my first tests the DC name was different from the original cluster but I have since recreated the cluster ensuring the DC names are identical and am still getting the same problem

**Comment by baileygm** [comment]
I had success doing similar restore tests with Cassandra 4.0.1 and Reaper 0.11.3
In my test case though the cluster topology of the source and target clusters were the same
I'll do further tests to try and prove whether the problem was caused by the reaper version or the topology differences

**Comment by adejanovski** [comment]
oooh I missed the part where it was an older version of Medusa 🤔 
Thanks

**Comment by baileygm** [comment]
I can't repeat the issue of the auth table corruption when using Reaper 0.11.3 so will close this issue
Thanks for your help
