### ISSUE TITLE
Doc restore not clear in case of full distant restore on cluster with same number of nodes

### ISSUE THREAD

**Issue by crystalloide** [thelastpickle/cassandra-medusa#441]
We can read in doc : 

[](https://github.com/thelastpickle/cassandra-medusa/blob/master/docs/images/cassandra_medusa_restore_case_2.png)Case #2 - Restore To A Different Cluster With Same Number Of Nodes
Restoring to a different cluster with the same number of nodes is a little harder because:

The destination cluster may have a different name, which is stored in system.local table.
The nodes may have different names.
The nodes may have different token assignments.
Medusa for Apache Cassandra Full Backups

Use the following command to run a remote restore:

$ medusa restore-cluster --backup-name=<name of the backup> \
                         [--host-list <mapping file>]
The optional host-list parameter tells Medusa how to map from the original backup nodes to the destination nodes in the new cluster, which is assumed to be a working Cassandra cluster. The mapping file must be a Command Separated File (without a heading row) with the following columns:

is_seed: True or False indicating if the destination node is a seed node. So we can restore and start the seed nodes first.
target_node: Host name of a node in the target cluster.
source_node: Host name of a source node to copy the backup data from.
For example:

True,new_node1.foo.net,old_node1.foo.net
True,new_node2.foo.net,old_node2.foo.net
False,new_node3.foo.net,old_node3.foo.net
If host-list is not provided, Medusa will map nodes by itself and enforce token assignments by updating the cassandra.yaml file.

In addition to the steps listed for Case 1 above, when performing a backup to a remote cluster the following steps are taken:

**_The system.local and system.peers tables are not modified to preserve the cluster name and prevent the target cluster from connecting to the source cluster._**
The system_auth keyspace is restored from the backup, unless the --keep-auth flag is passed to the restore command.
Token ownership is updated on the target nodes to match the source nodes by passing the -Dcassandra.initial_token JVM parameter when the node is restarted. Which causes ownership to be updated in the local system keyspace.

=> Is The sentence is not the opposite of that is done ?
I should have thought this  : 
The system.local and system.peers tables fo the restore cluster are modified to prevent the target cluster from connecting to the source cluster. 

kind regards

**Comment by adejanovski** [comment]
Hi @crystalloide,

when we say that the tables are not modified, it means we're not overwriting the existing local and peers tables on the target cluster with the ones from the backup. 
I understand how it can be taken as "we're restoring the tables unmodified using the backup" :)
To make it much simpler: those tables are not restored at all from the backup.
