### ISSUE TITLE
docker: /usr/bin/python3: No module named medusa.service.grpc.restore

### ISSUE THREAD

**Issue by maxbrunet** [thelastpickle/cassandra-medusa#443]
While testing #442, I found that restore does not work with the Docker image since v0.12.0:

```
MEDUSA_MODE = RESTORE
sleeping for 0 sec
Running Medusa in restore mode
Restoring backup medusa-default-backup1
/usr/bin/python3: No module named medusa.service.grpc.restore
```

The problematic line:

https://github.com/thelastpickle/cassandra-medusa/blob/e7de031389947562a32ef98e2c581abad7a5ec9d/k8s/docker-entrypoint.sh#L44

This module was thought to be unused and removed in #383:

> Remove dead code as the grpc/restore.py script isn't used anywhere.

**Comment by adejanovski** [comment]
Thanks for reporting this, I was under the impression that we had reintroduced the file already 😓 

It was just fixed and released in v0.12.1.
