### ISSUE TITLE
Purge should account for nodes that have been decommissioned

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-medusa#447]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13938573)

Purge is required to run on all nodes as it will only focus on the local node data.
If a node is decommissioned or replaced, its backups will remain forever in the storage backend.
We must come up with a way of deleting outdated backups for removed nodes.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1385) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1385
┆priority: Medium

**Comment by shelman** [comment]
+1 to this. We're using medusa for backups and a global purge that could run on a central machine and purge old backups across the whole cluster would be a great feature. 

In general, love the tool and thanks for all your hard work on it!

**Comment by adejanovski** [comment]
Thanks for your feedback @shelman 🙏
