### ISSUE TITLE
Unable to backup over secure port? (9142)

### ISSUE THREAD

**Issue by JohnBelliveau** [thelastpickle/cassandra-medusa#45]
We have a requirement that all data in transit must be encrypted, so we have disabled traffic to the default port (9042) and enabled SSL on port 9142. 

medusa fails with this error (IP addresses masked):
ERROR: This error happened during the backup: ('Unable to connect to any servers', {'xx.xxx.xx.xxx:9042': OSError(None, "Tried connecting to [('xx.xxx.xx.xxx', 9042)]. Last error: timed out")})
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/medusa/backup.py", line 252, in main
    schema, tokenmap = get_schema_and_tokenmap(cassandra)
  File "/usr/local/lib/python3.6/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.6/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.6/dist-packages/medusa/backup.py", line 296, in get_schema_and_tokenmap
    with cassandra.new_session() as cql_session:
  File "/usr/local/lib/python3.6/dist-packages/medusa/cassandra_utils.py", line 267, in new_session
    return self._cql_session_provider.new_session()
  File "/usr/local/lib/python3.6/dist-packages/medusa/cassandra_utils.py", line 86, in new_session
    session = cluster.connect()
  File "cassandra/cluster.py", line 1429, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1465, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1452, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 2996, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3041, in cassandra.cluster.ControlConnection._reconnect_internal

Is there any way to configure medusa to connect to Cassandra securely?

Thanks,
John

**Comment by sparshneel** [comment]
i am getting same issue @JohnBelliveau where u guys able to resolve this

**Comment by sparshneel** [comment]
cassandra-medusa uses cassandra.cluster from python lib from Datastax it defaults 9042.

**Comment by sparshneel** [comment]
So i fixed the issue by changing this    

**Cassandra_utils.py**

def __init__(self, ip_addresses, *, username=None, password=None):
        self._ip_addresses = ip_addresses

        auth_provider = PlainTextAuthProvider(username=username, password=password) if username and password else None
        self._auth_provider = auth_provider

        load_balancing_policy = WhiteListRoundRobinPolicy(ip_addresses)
        self._execution_profiles = {
            'local': ExecutionProfile(load_balancing_policy=load_balancing_policy)
        }
        **self._port=9142**
     def new_session(self, retry=False):
        """
        Creates a new CQL session. If retry is True then attempt to create a CQL session with retry logic. The max
        number of retries is currently hard coded at 5 and the delay between attempts is also hard coded at 5 sec. If
        no session can be created after the max retries is reached, an exception is raised.
         """

        cluster = Cluster(contact_points=self._ip_addresses,
                          auth_provider=self._auth_provider,
                          execution_profiles=self._execution_profiles, **port=self._port**)

**Comment by sparshneel** [comment]
this is temporary fix though

**Comment by JohnBelliveau** [comment]
Thanks @sparshneel, but this only addresses the port number challenge. When connecting using SSL, one would need to specify java keystore and truststore as in casssandra.yaml.

Otherwise, medusa will throw **ConnectionResetError(104, 'Connection reset by peer')**
and in the system.log, we will notice **io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record** info messages corresponding to the connection attempts

**Comment by adejanovski** [comment]
Hi @JohnBelliveau,

indeed Medusa doesn't yet support encrypted client to server connections with the Python driver.
We yet have to implement this feature (or have it contributed).

**Comment by arodrime** [comment]
Hello @JohnBelliveau, a patch is to be reviewed for this. It seems it's to be fixed within the following PR: https://github.com/thelastpickle/cassandra-medusa/pull/119. 

Would test this to help the author of the PR and confirm it works for you? We will also review and test, but if you need the patch, this PR might do.

**Comment by adejanovski** [comment]
This was fixed by #122 which just got merged to `master`.
We'll hopefully cut out a release soon with this feature.
