### ISSUE TITLE
Slack invite links to a non-public slack

### ISSUE THREAD

**Issue by Dutchy-** [thelastpickle/cassandra-medusa#451]
The readme says that for user questions we can go to http://s.apache.org/slack-invite. However, this is not a public slack. is there another place where I can ask questions?

**Comment by adejanovski** [comment]
You can here, but the Apache Slack workspace is the only place where you can chat with the community.
Do you need help getting access to the workspace?

**Comment by Dutchy-** [comment]
Well if that channel is still intended as a public community I would indeed like access. However, the https://infra.apache.org/slack.html (the bit about guests) did not make it clear to me that it is indeed a public community.

**Comment by adejanovski** [comment]
I agree it's not obvious, but things were made less convenient to prevent spammers from taking advantage of the workspace. Could you send me an email at alex.dejanovski at datastax.com and I'll send you an invite for the ASF Slack.
