### ISSUE TITLE
Medusa purge removing backups earlier than max_backup_age

### ISSUE THREAD

**Issue by sandeepmallik** [thelastpickle/cassandra-medusa#485]
Medusa purge is removing backups from other hosts. When I run purge on 192.126.191.10, medusa is removing backups from other 3 hosts. I believe it is some to do with last octet pattern 10/102/104/105. All have 10 as common (first 2 digits).  Medusa is not verifying ip's properly.

Didn't use FQDN as DNS is not configured.  If you see below config, medusa has to purge backups older than 14 days but it is removing them much earlier that too on hosts with pattern 10/102/104/105. **This is happening only on node 192.126.191.10. For now, I have disabled purge on 192.126.191.10.** We have cluster with 62 nodes. So, medusa purge is added to cron for all 62 nodes.

Using command -  medusa backup as we want to restrict backups to a single DC.

I believe there is race condition here. No. of completed backup = 7. No. of hosts where purge happened = 4. 7*4 = 28 which is max_backup_count. So, medusa is removing backups from those hosts as it is thinking max_backup_count threshold has been reached.

So three issues here.

1. Medusa removing backups earlier than max_backup_age.
2. This is effecting only with ip's pattern - 10/102/104/105.  As ip's are stored in order in backup_index, may be medusa is picking in that order.
3. Medusa should list backups to be purged for local node only. Here, it is listing other nodes backup that are being purged. If I am not wrong, purge should work on local node only. 

**resolve_ip_addresses = False
max_backup_age = 14
max_backup_count = 28
backup_grace_period_in_days = 10**

$ medusa purge
[2022-06-18 23:26:21,889] INFO: Monitoring provider is noop
[2022-06-18 23:26:21,889] INFO: Starting purge
**[2022-06-18 23:26:22,746] INFO: Listing backups for 192.126.191.10
[2022-06-18 23:26:23,430] INFO: 4 backups are candidate to be purged
[2022-06-18 23:26:23,430] INFO: Purging backup s3_test_06_15_2022_11 from node 192.126.191.102...
[2022-06-18 23:26:23,770] INFO: Purging backup s3_test_06_15_2022_11 from node 192.126.191.105...
[2022-06-18 23:26:24,132] INFO: Purging backup s3_test_06_15_2022_11 from node 192.126.191.104...
[2022-06-18 23:26:24,525] INFO: Purging backup s3_test_06_15_2022_11 from node 192.126.191.10...
[2022-06-18 23:26:24,898] INFO: Cleaning up orphaned files for 192.126.191.104...
[2022-06-18 23:26:46,270] INFO: Cleaning up orphaned files for 192.126.191.102...
[2022-06-18 23:27:06,812] INFO: Cleaning up orphaned files for 192.126.191.105...
[2022-06-18 23:27:28,564] INFO: Cleaning up orphaned files for 192.126.191.10...**
[2022-06-18 23:27:54,886] INFO: Purged 16 objects with a total size of 41.62 MB
[2022-06-18 23:27:54,886] INFO: 70653 objects within 10 days grace period were not deleted

$ medusa list-backups
**s3_test_06_15_2022_11 (started: 2022-06-15 11:00:10, finished: Incomplete [58 of 62 nodes finished])**
s3_test_06_15_2022_23 (started: 2022-06-15 23:01:51, finished: 2022-06-15 23:50:43)
s3_test_06_16_2022_11 (started: 2022-06-16 11:00:12, finished: 2022-06-16 12:22:06)
s3_test_06_16_2022_23 (started: 2022-06-16 23:02:30, finished: 2022-06-17 00:05:26)
s3_test_06_17_2022_11 (started: 2022-06-17 11:00:12, finished: 2022-06-17 12:03:57)
s3_test_06_17_2022_23 (started: 2022-06-17 23:00:11, finished: 2022-06-18 00:10:19)
s3_test_06_18_2022_11 (started: 2022-06-18 11:02:27, finished: 2022-06-18 12:02:10)
s3_test_06_18_2022_23 (started: 2022-06-18 23:00:17, finished: 2022-06-19 00:48:48)

$ medusa status --backup-name s3_prod_06_15_2022_11
s3_prod_06_15_2022_11 [Incomplete!]

* Started: 2022-06-15 11:00:10, Finished: never
* 58 nodes completed, 0 nodes incomplete, 4 nodes missing
* Missing nodes:
    **192.126.191.10
    192.126.191.104
    192.126.191.105
    192.126.191.102**
* 3473864 files, 78.53 TB

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1584) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1584
┆priority: Medium

**Comment by adejanovski** [comment]
Hi @sandeepmallik, which version of Medusa are you running?
I think the bug you're hitting was fixed by [this PR](https://github.com/thelastpickle/cassandra-medusa/pull/450) which was released in v0.13.0.

**Comment by sandeepmallik** [comment]
@adejanovski I am using Medusa 0.13.1

**Comment by sandeepmallik** [comment]
Thanks @adejanovski
