### ISSUE TITLE
Purge don't delete the folders in S3 Compatible storage

### ISSUE THREAD

**Issue by nurlan-issin** [thelastpickle/cassandra-medusa#488]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952007)

I'm use Medusa to backup Cassandra cluster to Seaweedfs S3-compatible storage.
After running the purge the Medusa keep empty folders in storage.
This is inconvenient when viewing the contents of the storage.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1599) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1599
┆priority: Medium

**Comment by rzvoncek** [comment]
Hi @nurlan-issin . We've changed the libraries we use for interacting with storage. The issue you've been facing probably morphed into something new. We can't easily get access to Seaweedfs, so could you perhaps try it yourself?
