### ISSUE TITLE
Allow Medusa to take CQL credentials through a file

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-medusa#493]
The K8ssandra-operator modular secrets backend requires the ability for Medusa to read CQL credentials from files. Currently only environment variables are supported.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1619) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1619
┆priority: Medium

**Comment by ufoot** [comment]
Hi @adejanovski , I am proposing this PR https://github.com/thelastpickle/cassandra-medusa/pull/552 to address this task.
