### ISSUE TITLE
Differeence between in-place restore-cluster and restore-node with option --table ks.ts1 from the same diff. backup 

### ISSUE THREAD

**Issue by m934030039** [thelastpickle/cassandra-medusa#496]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13937858)

Hi,

Any difference results between below ?

For example, we have 10 nodes (3 seed nodes,RF=3) with diff. backup to S3, periodicly for 10 days.

**To perform on one node with pssh utility.**

# medusa **restore-cluster --table ks.ts1** --temp-dir /backup/restore --backup-name s3.diff_restore_testing --in-place
**To perform node by node one at a time.**

# medusa **restore-node --table ks.ts1** --temp-dir /backup/restore --backup-name s3.diff_restore_testing --in-place
**Theoretically, we expect both of results should be the same.**

In reality, the case #1 is ok but something wrong on the case #2.

We are looking into this.

We are using Medusa version 0.11.x 

-Sheng

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1647) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-1647
┆priority: Medium
┆Link To Issue: https://k8ssandra.atlassian.net/browse/K8SSAND-1647

**Comment by adejanovski** [comment]
`restore-cluster` performs orchestration that pssh won't.
If you can provide some logs on what's going wrong precisely, it would be helpful to investigate this.

**Comment by nguyenthai0107** [comment]
Hello @m934030039 
Have a nice day.
Just a question for you with your cluster cassandra.
So when run backup. did you run backups on 3 seeds hosts or just only 1 seed host.
Thank you.

**Comment by m934030039** [comment]
Hi,

All nodes includes seed nodes.

-Sheng
