### ISSUE TITLE
Allow multiple commands to stop/start cassandra

### ISSUE THREAD

**Issue by kaushalkumar** [thelastpickle/cassandra-medusa#498]
While restoring backup using restore-cluster command we see that medusa uses "service cassandra stop" command to stop the cassandra node. There is a configuration stop_cmd which can be modified to use a custom command. We have tried to use it, but it does not work in our setup.

In our setup we have used supervisorctl to control the cassandra service and we manage our cluster using puppet. Thus in order to stop cassandra we have to do following
`systemctl stop puppet && supervisorctl stop smc`

When we try to use this via medusa.ini, then we get an error during execution of subprocess.checkoutput. Ref: https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/cassandra_utils.py#L542

We observe that default value (False) of `shell` is used during invocation of `subprocess.checkoutput` so the command fails. It is also seen that shell is set to True at few places. Ref: https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/cassandra_utils.py#L559

Can you please check and see if this can be enhanced to allow multiple commands to stop/start cassandra

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1649) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-1649
┆priority: Medium
┆Link To Issue: https://k8ssandra.atlassian.net/browse/K8SSAND-1649

**Comment by adejanovski** [comment]
Have you tried setting `shell` to `True` to see if it fixes the issue?
Also, don't these commands require `sudo` to work properly?
Have you tried to run just one of these two commands to see if it's the combination of commands that fails or all commands?
If you happen to have a fix that works, I encourage you to submit a PR that we can review.

**Comment by adejanovski** [comment]
Closing as stale
