### ISSUE TITLE
Support of timeout in medusa

### ISSUE THREAD

**Issue by kaushalkumar** [thelastpickle/cassandra-medusa#502]
Hi - Can you please let us know if there are timeout configuration available, such that users can customize those for their usage.
Something like

1. Command timeout 
1. Connection timeout

Regards

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1669) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1669
┆priority: Medium

**Comment by adejanovski** [comment]
There are no such timeouts available. Backups can take a very long time depending on several factors, and the need hasn't been expressed so far.
Libcloud and the cli tools we rely on have their own timeouts though, which prevents from having a hanging backup job.

**Comment by rzvoncek** [comment]
Closing as answered.
