### ISSUE TITLE
list-backups does not indicates the backup type - full or differential

### ISSUE THREAD

**Issue by kaushalkumar** [thelastpickle/cassandra-medusa#503]
Hi - Can you please let us know if there is any API available to get the type of backup (full or differential). We have explored list-backups but could not get this information.

```
[root@node1-dc1 cassandra_backups]# medusa list-backups --show-all
[2022-07-12 06:09:07,748] INFO: Resolving ip address
[2022-07-12 06:09:07,749] INFO: ip address to resolve 111.222.333.4
data070820221111 (started: 2022-07-08 01:41:16, finished: Incomplete [2 of 3 nodes finished])
data070820221634 (started: 2022-07-08 07:04:58, finished: Incomplete [2 of 3 nodes finished])
data070820221638 (started: 2022-07-08 07:08:08, finished: Incomplete [2 of 3 nodes finished])
data071120221134 (started: 2022-07-11 02:04:24, finished: 2022-07-11 02:04:41)
data071220221453 (started: 2022-07-12 05:31:07, finished: 2022-07-12 05:31:26)
data071220221502 (started: 2022-07-12 05:32:06, finished: 2022-07-12 05:32:15)
data071220221503 (started: 2022-07-12 05:32:58, finished: 2022-07-12 05:33:07)
```

Regards

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1670) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1670
┆priority: Medium

**Comment by adejanovski** [comment]
There's no way of getting that info from the available commands indeed. It could be easily added though in the `list-backups` command by adding something like this on line 56 of `listing.py`:

```
print('{} (started: {}, finished: {}, type: {})'.format(cluster_backup.name, started, finished, cluster_backup.backup_type))
```

**Comment by rzvoncek** [comment]
We have a vague plan of removing full backups, so extending the list command is unlikely to happen.
