### ISSUE TITLE
verify command output does not indicate md5 check result

### ISSUE THREAD

**Issue by kaushalkumar** [thelastpickle/cassandra-medusa#504]
Hi - verify command has an option to enable md5. check (via --enable-md5-checks), but the output of this command does not indicates anything related to md5 verification. The output is same irrespective of using this option or not using this option.

```
[root@node1-dc1 data]# medusa verify --backup-name=data071220221542
[2022-07-12 06:26:24,122] INFO: Resolving ip address
[2022-07-12 06:26:24,123] INFO: ip address to resolve 111.222.333.4
Validating data071220221542 ...
- Completion: OK!
- Manifest validated: OK!!

[root@node1-dc1 data]# medusa verify --backup-name=data071220221542 --enable-md5-checks
[2022-07-12 06:26:36,243] INFO: Resolving ip address
[2022-07-12 06:26:36,244] INFO: ip address to resolve 111.222.333.4
Validating data071220221542 ...
- Completion: OK!
- Manifest validated: OK!!
```

Can you please check it.

Regards,

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1671) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1671
┆priority: Medium

**Comment by adejanovski** [comment]
The md5 check is an additional one embedded in the manifest validation. You have the same outputs because the md5 checks passed successfully.
If you had a failed md5 check, you'd see additional outputs indicating which files didn't match with the manifest.

**Comment by rzvoncek** [comment]
Closing as answered.
