### ISSUE TITLE
support of backup-cluster via grpc service

### ISSUE THREAD

**Issue by kaushalkumar** [thelastpickle/cassandra-medusa#511]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952000)

Hi - grpc service provides an API for backup, which creates a backup for a node. Is there any plan for support of backup-cluster via grpc.

Regards

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1712) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1712
┆priority: Medium

**Comment by adejanovski** [comment]
no, we don't intend to implement this. Coordination for cluster backups in the GRPC context has to be built above this and is outside of Medusa's scope.
