### ISSUE TITLE
grpc service - port number configurability

### ISSUE THREAD

**Issue by kaushalkumar** [thelastpickle/cassandra-medusa#512]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13951998)

Hi - While exploring grpc service, it was noticed that the server starts at a fixed port number 50051. Is there any configuration available to alter this port number.
Regards,

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/MED-42) by [Unito](https://www.unito.io)
┆Issue Number: MED-42

**Comment by rzvoncek** [comment]
We still don't support configuring the gRPC port.
