### ISSUE TITLE
medusa (grpc) - Restore functionality

### ISSUE THREAD

**Issue by kaushalkumar** [thelastpickle/cassandra-medusa#513]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13951997)

Hi - We are trying to check if we can use medusa via grpc. In this sequence we need some clarity on following. Can you please help us in the same

1. Does medusa's grpc server support restore backup functionality.
1. If it support then does it support a node level restore or cluster (data center) level restore
1. If restore is supported, then does it have any option of enabling/using sstableloader (to avoid server stop/start)
1. We see an API named "prepareRestore". What is the functionality for this
1. In prepareRestore API - What is the role of arguments "datacenter" and "restoreKey"

Regards

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1714) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1714
┆priority: Medium

**Comment by rzvoncek** [comment]
Hi @kaushalkumar . Sorry for getting back to you so late, but it's only now I got to do a proper grooming of the issues. Is any of this still relevant?
