### ISSUE TITLE
restore_node is not restoring keyspaces on a new node

### ISSUE THREAD

**Issue by kaushalkumar** [thelastpickle/cassandra-medusa#517]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13951989)

Hi - We took a backup (of a 2dc, 3 nodes/dc cassandra database)  using medusa's backup command and copy the same to a new cluster.
In the new cluster we tried to restore the backup using restore-node command and found that the keyspaces in the backup are not restore. The debug level log says "Skipping file me-1-big-Data.db: table keyspace_1.tbl_test doesn't exist".
While scanning the code it is observed that restore-cluster creates the schema but restore-node does not. Can you please suggest the steps to be executed to restore data using restore-node command.

We are planning to use medusa via kubernetes and were having an opinion that restoring data on a new cluster will be a fairly easy step, but we found that restore-node is used in kubernetes and restore-node does not restores our keyspaces. 

Looking forward for you response. 

Regards,
Kaushal

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1750) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1750
┆priority: Medium

**Comment by rzvoncek** [comment]
Hello @kaushalkumar. Again, sorry for coming so late to the rescue. Are you still facing this?
