### ISSUE TITLE
how config ceph in k8ssandra 

### ISSUE THREAD

**Issue by amine-limonade** [thelastpickle/cassandra-medusa#518]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13951986)

medusa.storage_properties: 
    host:

i don't know how do the config of ceph  in medusa

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1765) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1765
┆priority: Medium

**Comment by rzvoncek** [comment]
Hello @amine-limonade ! Sorry for coming so late to this, but only now I've gotten to do a proper grooming of everything. Any chance you managed to work this out? If not and you moved on, that's okay too :)
