### ISSUE TITLE
how set in host = rgw_host for ceph config medusa

### ISSUE THREAD

**Issue by amine-limonade** [thelastpickle/cassandra-medusa#519]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13951985)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1767) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1767
┆priority: Medium

**Comment by rzvoncek** [comment]
Hello. I'm not sure fully understand the question. @amine-limonade , if this is still relevant for you, could you please elaborate?
