### ISSUE TITLE
gRPC API (PrepareRestore) does not throw error when incorrect backup name is provided

### ISSUE THREAD

**Issue by kaushalkumar** [thelastpickle/cassandra-medusa#527]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13951978)

Hi,
The PrepareRestore API does not throw an expected exception when incorrect backup name is provided. Due to the unavailabiltity of the exception, user proceeds with restore via initContainers of medusa, which does not work.

To fix this, one approach could be to update [PrepareRestore](https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/service/grpc/server.py#L260) API and throw an error after [for loop ](https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/service/grpc/server.py#L265)(when backup is not found).

Regards,
Kaushal

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1807) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1807
┆priority: Medium

**Comment by adejanovski** [comment]
We don't use the PrepareRestore endpoint anymore to compute the mapping. This is fully done within the operator.
