### ISSUE TITLE
GitHub actions build fails due to "permission error"

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-medusa#54]
It seems like builds have started failing due to `/etc/medusa` not being writeable anymore when running tox. 
I've tried to fix this by running a chmod on `/etc/` but then it fails on a weird error when downloading flake8 from pypi : https://github.com/thelastpickle/cassandra-medusa/runs/380888511

**Comment by arodrime** [comment]
The fix was merged here: https://github.com/thelastpickle/cassandra-medusa/pull/55

Closing this issue.
