### ISSUE TITLE
Consider Poetry for package version control

### ISSUE THREAD

**Issue by caniko** [thelastpickle/cassandra-medusa#555]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=19051419)

Poetry being a great tool for developers is also very useful for locking versions of upstream packages. I think it is nice-to-have in these enterprise-level applications. At least consider switching to `pyproject.toml` using the setuptools format.

https://python-poetry.org/

**Comment by adejanovski** [comment]
@caniko, that sounds like a great idea. Is this something you'd be willing to contribute?
