### ISSUE TITLE
Seeing `Library not loaded: @rpath/libssh.4.dylib` Error on MacOS

### ISSUE THREAD

**Issue by shanmu9898** [thelastpickle/cassandra-medusa#565]
Installing and running medusa gives the following error

`ImportError: dlopen(/Users/bumblebee/opt/anaconda3/lib/python3.8/site-packages/ssh/options.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libssh.4.dylib`

Platform used: Mac OS Ventura
Python Version 3.8

Do let me know if any more information is required. Thank you!

**Comment by adejanovski** [comment]
You're probably missing some dependencies.
Maybe you can try installing libssh and libssh2 with homebrew:

```
brew install libssh
brew install libssh2
```

**Comment by rzvoncek** [comment]
I've also been having issues with this. Not neccesarily running Medusa itself, but it ITs. 
I'm using Anaconda to manage my python evns, so for me the solution was to:
```
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/Users/<me>/anaconda3/pkgs/libssh2-1.10.0-h02f6b3c_2/lib:/opt/homebrew/Cellar/libssh/0.10.5_1/lib"
```
Then ITs worked. 

#555 might help with this, but beyond that, I don't think we can do much more to accomodate Macs :-/
