### ISSUE TITLE
Allow specifying storage class name when uploading backups to S3

### ISSUE THREAD

**Issue by mohammad-aburadeh** [thelastpickle/cassandra-medusa#568]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=23371658)

Medusa does not support specifying the storage class name when uploading backups to S3/GCP/Azure.
This is very important for many customers as it can help to reduce the storage cost.

In my case, I manage more than 30 Cassandra clusters. We are storing more than 1000TB of backups in S3.

**Comment by rzvoncek** [comment]
Hi @mohammad-aburadeh ! It'd just like to let you know we did not forget about this, it's just hard to squeeze this into our sprints. In case you would manage to come up with a PR, we'd be super grateful.

**Comment by mohammad-aburadeh** [comment]
Hi @rzvoncek 

I just submitted a PR to implement this feature: 
https://github.com/thelastpickle/cassandra-medusa/pull/737
