### ISSUE TITLE
Question about max bandwidth and status of restore

### ISSUE THREAD

**Issue by yanzakha** [thelastpickle/cassandra-medusa#594]
Hello, I have a question. Is max bandwidth parameter in medusa conf limit for all medusa agents in summary or every separate agent?
And the second question is maybe there is some option to show cluster-restore progress?

**Comment by adejanovski** [comment]
The max bandwidth parameter is a global one, not per upload.
There is no option to show cluster restore progress, but that would be a great feature indeed.

**Comment by yanzakha** [comment]
Thanks for your reply!
