### ISSUE TITLE
Concern about seed_hosts when run backup

### ISSUE THREAD

**Issue by nguyenthai0107** [thelastpickle/cassandra-medusa#626]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=37160968)

Hello everyones.
Just concern that what if for example, i has a cluster cassandra with 5 nodes and 2 of them was seed_host.
So question is do i need run backup on 2 seeds_hosts
Ex:
seed 1 : /usr/local/bin/medusa -vv backup-cluster --backup-name "A-seed-1" --mode full
seed 2:  /usr/local/bin/medusa -vv backup-cluster --backup-name "B-seed-2" --mode full
And i can run 2 command on 2 seeds_hosts at the same time .
Thank you so much.
Regards.

**Comment by adejanovski** [comment]
Hi, 

backup-cluster should run only once in the cluster, and it doesn't have to run from a seed host.
All nodes in the cluster will be backed up as part of the process.

I do not recommend running full backups, they have only disavantages compared to differential ones.

**Comment by nguyenthai0107** [comment]
Hi, 
Thanks for reply.
"backup-cluster should run only once in the cluster, and it doesn't have to run from a seed host."
=> Is that your mean when run backup-cluster ( fulll or diffierential ) i can run script in ONE 1st seed_host ( I have 2 seeds ) OR can run backup-cluster on 4th host ( NOT seed ) right ?
Just confirm.
Thank you.

**Comment by adejanovski** [comment]
You can run backup-cluster on any host in the cluster, it doesn't have to be a seed.

**Comment by adejanovski** [comment]
I'll go ahead and close this ticket. Feel free to reopen if you still have questions.
