### ISSUE TITLE
Storage/S3 - _stat_blob() should not do a list after it does a head

### ISSUE THREAD

**Issue by rzvoncek** [thelastpickle/cassandra-medusa#629]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=37337659)

Currently, we do a head() on an object, and then do a list_objects with a prefix of that object full key.

The list is redundant because the head() already returns the `Etag` header and `Content-Length` for the size.

## Definition of done

- [ ] When stating an object in S3, only one request is issued to the storage backend.

**Comment by adejanovski** [comment]
@rzvoncek, I assume this is no longer relevant with the move to Boto3, right?

**Comment by rzvoncek** [comment]
Yes, the boto work handles this. Closing.
