### ISSUE TITLE
Backup only specific keyspace(s)

### ISSUE THREAD

**Issue by nicholasamorim** [thelastpickle/cassandra-medusa#64]
It is possible to recover a single keyspace. Is there any particular reason it is not possible to backup only one keyspace?

Would that be a simple addition?

**Comment by adejanovski** [comment]
Backing up only a subset of keyspaces could be dangerous and make things more complex when we deal with restores.
How do we know a backup is only for some keyspaces/tables?
How do we deal with such backups at restore time? Do we wipe all data or just the keyspaces/tables that were backed up?

I guess we could adjust the configuration to blacklist some keyspaces, which could be easy enough (no additional flag), but we need to give some thoughts on what could go wrong with partial backups.

**Comment by nicholasamorim** [comment]
The main reason I thought this would be simple it's because restoring a single keyspace is possible.

> How do we know a backup is only for some keyspaces/tables?
> How do we deal with such backups at restore time? Do we wipe all data or just the keyspaces/tables that were backed up?

I agree, you're absolutely right. By me, we can close this and can be kept for reference on reasoning only.
