### ISSUE TITLE
Purge leaves behind incomplete backups... forever!

### ISSUE THREAD

**Issue by arodrime** [thelastpickle/cassandra-medusa#66]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952160)

michaelsembwever reported an issue as he had no way to remove incomplete backups during his tests:

* No delete function - addressed in #18 
* **No purge of incomplete backups**. That's what we should fix here.

This leaves the user with no way of cleaning backups without accessing the data storage and delete files, hoping to do it right or leave the data behind forever.

It seems this is all about making purge considering any started backup instead of only checking the complete backups.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-325) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-325

**Comment by adejanovski** [comment]
It's not really that purge skips incomplete backups, rather than it makes it fail because the manifest file is missing, which triggers an exception.
We need to make it possible to delete such backups by catching the exception and acting accordingly.

**Comment by rzvoncek** [comment]
This is very likely getting addressed in https://github.com/thelastpickle/cassandra-medusa/issues/607. Closing this as a duplicate.
