### ISSUE TITLE
Use the strongest constraint for purges

### ISSUE THREAD

**Issue by arodrime** [thelastpickle/cassandra-medusa#67]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952158)

When purging old backups, there are 2 options:

* Remove backups older than X
* Do not keep more than Y backups (a count).

Here michaelsembwever reported that when setting X to 30 days and Y (the count) to 15, with a daily backup, it seems that we are not respecting the second rule and go over the 15 backups and keeping the 30 backups (1 per day for 30 days).

The more natural behavior here would probably to apply the most strict constraint when both are set.

To express it more clear, the purge should trigger as soon as any constraint of the constraints is reached. In my example we should have no more than 15 backups and 15 days of history, not 30 as we medusa will purge after that.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-326) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-326

**Comment by adejanovski** [comment]
I pretty sure it's the case already.
If a backup falls into one or the other condition, it will get purged.
The way the code is architected, we scan all backups for both conditions, and join the resulting lists into one. This final list is iterated and each backup will then get deleted.
Then the last phase is a global pass on all remaining backups manifest file, and clean up sstable files that don't belong to any of the remaining ones.

**Comment by rzvoncek** [comment]
I've recently touched the purge code in https://github.com/thelastpickle/cassandra-medusa/issues/607 and I confirm that it works as Alex describes. Once we're done with the #607, this will work properly.
