### ISSUE TITLE
Azure Storage Support for different Cloud Contexts (e.g. AzureUSGovernment)

### ISSUE THREAD

**Issue by ernstae** [thelastpickle/cassandra-medusa#680]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=43950753)

## Overview
Azure Storage looks to be configured for only Commercial cloud on line https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/storage/azure_storage.py#L58 _windows.net_

In AzureUSGovernment cloud, the URLs end with `usgovcloudapi.net`.

The Azure SDK allows for the appropriate cloud context to be set, and with the original azure-cli implementation of storage that was possible `< 0.16.0`.

## The Ask
The connection string for Azure Blob Storage should support a conditional so that it can *either* be the current `blob.core.windows.net` for "Azure" cloud or `blob.core.usgovcloudapi.net` for "AzureUSGovernment" cloud.  
This should be configurable in the medusa configuration file, rather than hard-coded in the above-referenced file.

_I'd code this up and offer a patch, but I don't immediately have the time, and hoped that the maintainers and existing contributors could tackle that faster than I can_

## Additional Azure References
https://learn.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure

![Screen Shot 2023-11-07 at 3 18 07 PM](https://github.com/thelastpickle/cassandra-medusa/assets/3441274/bf9aaed7-88a1-43bb-9882-b621d728dcd2)

**Comment by rzvoncek** [comment]
Hello @ernstae! Thanks for raising this. The task seems fairly straightforward, so I might be able to squeeze it into our current iteration.

**Comment by rzvoncek** [comment]
Hi @ernstae , perhaps you've noticed already, but I now have #685 out.
I debated how precisely to do this. In the end I decided to use the `host` field in the `config/storage` section to specify the _domain_ that is different for the gov cloud. 
We don't have access to the US GOV Azure region, so I can only do unit tests and ask you if:
* This sort of solution works for you.
* Give it a try out and let us know if it works.

**Comment by ernstae** [comment]
> Hi @ernstae , perhaps you've noticed already, but I now have #685 out. I debated how precisely to do this. In the end I decided to use the `host` field in the `config/storage` section to specify the _domain_ that is different for the gov cloud. We don't have access to the US GOV Azure region, so I can only do unit tests and ask you if:
> 
> * This sort of solution works for you.
> * Give it a try out and let us know if it works.

Sorry for the very delayed response (between time off, holidays and health issues).  I'll see if I can do a test of this in the not-so-distant future.  Thank you for your contribution and grabbing it so quickly, @rzvoncek
