### ISSUE TITLE
Question on snapshot behavior with S3 storage

### ISSUE THREAD

**Issue by pdpol** [thelastpickle/cassandra-medusa#688]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=46019837)

Hi,

I'm looking for clarification on what the expected behavior is for Medusa for storing snapshots locally when S3 storage is enabled.

I recently re-enabled automated weekly Medusa differential backups on two Cassandra clusters after someone discovered they had stopped running for a long time. I can confirm that snapshots are successfully uploaded to the configured S3 bucket for our cluster, but we were surprised recently to see a massive amount of disk utilization increase on nodes locally in the weeks after re-enabling, with some nodes now approaching dangerously low levels of free disk space.

We found that there are indeed a list of files in the snapshot directories for these partitions that look akin to:
```
26G	medusa-main-cluster-10-16-2023
28G	medusa-main-cluster-11-20-2023
31G	medusa-main-cluster-11-06-2023
34G	medusa-main-cluster-11-27-2023
90G	medusa-main-cluster-11-13-2023
241G	medusa-main-cluster-10-23-2023
1.1T	medusa-main-cluster-10-30-2023
3.3T	medusa-main-cluster-10-10-2023
```

We also have a purge job set up to run with `max_backup_age=30` but it does not appear to have found any candidates for purge yet, although there are backups I see that fall outside of the max backup age range.

My question is whether or not it is expected for the local nodes to hold on to these snapshots after successfully uploading to S3, or if something might be misconfigured? This is something I was unable to find in the docs. Also apologies if this is not the right place for this kind of question, I tried to join the Slack channel but it doesn't seem like I can as an outsider to ASF.

**Comment by pdpol** [comment]
Thank you for the confirmation! Very helpful to know that it is indeed supposed to be cleaning up, and to see the command here we can run manually in the meantime to reclaim the space.

Some more details I'll throw out there - we have a coordinator running Medusa outside the actual clusters that orchestrates the backup runs. Automation is simply via cron. We run backups like this: 
```
medusa backup-cluster --backup-name main-cluster-$BACKUP_DATE --mode differential --seed-target 10.0.3.137 --parallel-uploads 1
```

As part of the work I had done to get them running again I upgraded the coordinator to 0.16.2 to support running with `rmiURLParsing=legacy` because our clusters are on 3.11.12 which expects ipv6 node addresses by default. Looking at the actual nodes in the Cassandra cluster I see that they're running Medusa at 0.11.0, so potentially upgrading across the cluster could be worthwhile?

**Comment by rzvoncek** [comment]
Hello, great to hear that you managed to untangle this a bit.
I don't think (a new) Medusa will manage to clear up the old snapshots automatically. You might need to ssh into each of the Cassandra containers and run something like `nodetool clearsnapshot -t medusa-main-cluster-10-16-2023` to get rid of them.

To mitigate these situations in the future, we can indeed add clearing snapshots of the same name as the backup being purged. This is pretty straightforward and should not take too much effort.

We are still left with snapshots that only exists on the source nodes but don't have any mention in the storage backend. 
Here, we could use the fact that we prefix all snapshits with `medusa-`, so it seems possible to discover all of them, take the ones older than `maxBackupAge` (or the ones older than the oldest backup seen in the storage) and clear them.

**Comment by rzvoncek** [comment]
Hi @pdpol ! I'm doing some grooming and stumbled across this. How's it going? Did you manage to work everything out?

**Comment by pdpol** [comment]
Hi @rzvoncek, sorry I forgot to update after my last message. I did upgrade both clusters to 0.16.2 and it actually did start removing snapshots again!

**Comment by rzvoncek** [comment]
Great to hear. So I'll go ahead and close this one. Please feel free to open a new one if you need to!
