### ISSUE TITLE
Medusa doesn't have option to zip backup file before upload to S3 bucket

### ISSUE THREAD

**Issue by arunshah2002** [thelastpickle/cassandra-medusa#699]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=48793672)

Hi,

I am looking for an option to zip the backup file before uploading to S3 bucket to save cost, also, for restore the same.

Please suggest.

**Comment by adejanovski** [comment]
Hi @arunshah2002,

Cassandra already compresses data stored in sstables and the gain here would be marginal.
This feature was already requested in the past and ruled out because the complexity it would add isn't worth the benefits we'd get out of it.

**Comment by arunshah2002** [comment]
Hi, thanks for your reponse on this request. I strongly agree that having this as feature would add complexity, however, organisation where apache cassandra being used and since there are no tools available for open source C* do see it as requirement since uploading raw sstable to s3 bucket consumes lot of space when compared to uploading the zipped files to save cost on bucket.

Thanks & Regards,
Arun Shah

**Comment by adejanovski** [comment]
Would you have numbers showing the expected savings in terms of storage size?

**Comment by arunshah2002** [comment]
Hi,

I would need a week times to capture the savings and share.


Thanks,
Arun Kumar Shah
9916950644



-------- Original message --------
From: Alexander Dejanovski ***@***.***>
Date: 02/01/24 10:03 pm (GMT+05:30)
To: thelastpickle/cassandra-medusa ***@***.***>
Cc: arunshah2002 ***@***.***>, State change ***@***.***>
Subject: Re: [thelastpickle/cassandra-medusa] Medusa doesn't have option to zip backup file before upload to S3 bucket (Issue #699)


Would you have numbers showing the expected savings in terms of storage size?

**Comment by arunshah2002** [comment]
Hi Alexander,

I did some analysis and see that we are storing 200+ TB data (14 days retention) in S3 bucket when zipped the backup files saving ~25% of S3 storage cost when compared to unzipped raw sstables.



Thanks,
Arun Kumar Shah
9916950644



-------- Original message --------
From: Alexander Dejanovski ***@***.***>
Date: 02/01/24 10:03 pm (GMT+05:30)
To: thelastpickle/cassandra-medusa ***@***.***>
Cc: arunshah2002 ***@***.***>, State change ***@***.***>
Subject: Re: [thelastpickle/cassandra-medusa] Medusa doesn't have option to zip backup file before upload to S3 bucket (Issue #699)


Would you have numbers showing the expected savings in terms of storage size?
