### ISSUE TITLE
Python 3.11+ PIP Dependencies

### ISSUE THREAD

**Issue by Nassz** [thelastpickle/cassandra-medusa#706]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=50107255)

After releasing breaking changes noted in : 
https://thelastpickle.com/blog/2023/09/21/medusa-v016-was-released.html

cassandra-medusa 0.17.1 still have some issues with  Python compatibility modules for 
`python-dateutil` etc. 

As well as some inconsistency in the repo for requirements.txt and setup.py 
![image](https://github.com/thelastpickle/cassandra-medusa/assets/9954591/ad69ef43-cec2-4188-a962-0fd76e786e28)

Thus, please review all Python requirements.

**Comment by rzvoncek** [comment]
Hi. Thanks for letting us know! This relates to #555.

**Comment by rzvoncek** [comment]
With #555, this is getting fixed.
