### ISSUE TITLE
Fix various CVEs

### ISSUE THREAD

**Issue by AlexsandroRotundo** [thelastpickle/cassandra-medusa#725]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=56613810)

I would try to fix some CVEs related to the old go version upgrading the grpc_health_probe library.

**Comment by rzvoncek** [comment]
Hi @AlexsandroRotundo! I might have missed your offer and recently fixed some CVEs (#726 and #727).
However, [this](https://github.com/thelastpickle/cassandra-medusa/security/code-scanning) still seems to list a few.

Although, I also see the #724 should have just closed this and it didn't. So perhaps let's close this one and open new ones for the items from the code-scanning.
