### ISSUE TITLE
medusa support upload files package and data compress

### ISSUE THREAD

**Issue by Maxwell-Guo** [thelastpickle/cassandra-medusa#73]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952155)

When doing backup the data of one generation number like : md-18-big got eight files , if when can tar then to one file  or tar the file under table dir to one file ,then the result file can do compress, afther doing compress we can upload the  final file to cloud storage. In this way we can saving network bandwidth as well as upload time and download time . for almost case cpu is ok to do compress.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-328) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-328

**Comment by Maxwell-Guo** [comment]
@adejanovski  what is your point of view ?

**Comment by adejanovski** [comment]
Hi @Maxwell-Guo,
I think most of the space lies in the *-Data* files, which are already compressed by Cassandra.
I wouldn't be adding this feature unless we have some numbers to support it.
How much would you expect to save on storage size/transfers? Did you run some experiments to verify these numbers?

**Comment by Maxwell-Guo** [comment]
hi @adejanovski ,  I have not run some experiments to verify these numbers, latter I will run the experiments. For some situations, I know it is not a goog choice to compress the data after cassandra already do this job, but some people may not do compress . Besides what is your point we tar the same md-big-version to one file ?

**Comment by adejanovski** [comment]
I currently do not see what benefit we would get from tar'ing the files of the same generation.
The complexity of implementing this change and supporting it over time might not be worth it.
Compressing files doesn't require to tar files together and at the opposite, it might be better to compress files other than the *-Data* files to avoid spending CPU cycles on an inefficient compression.
