### ISSUE TITLE
Allow Aws-cli to look for or accept different paths in case running in an venv

### ISSUE THREAD

**Issue by bishoprunout** [thelastpickle/cassandra-medusa#78]
Hello sometimes medusa isn't able to find awscli binary because it assumes its always installed the primary python environments. This issue arrives for me as I build an rpm which installs everything in a venv .

SO either provide a config value for it or dynamically try to find it like  so https://github.com/thelastpickle/cassandra-medusa/pull/77

Thanks I realize this request might be a little niche :)

**Comment by adejanovski** [comment]
Fixed by #77
