### ISSUE TITLE
Questions regarding cluster-restore using sstableloader

### ISSUE THREAD

**Issue by Eclion** [thelastpickle/cassandra-medusa#789]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=70176938)

Hi,

I understand from the [restore-cluster.py file](https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/restore_cluster.py#L385) that running a restore of a cluster using sstableloader requires the deletion of the previous data.
However, is it really needed ?

Also, is it really needed to delete all the keyspaces if we wish to restore only one keyspace or one table ?

**Comment by adejanovski** [comment]
It's the approach we've taken from the start. We could support single table/keyspace restores for in place restores, and probably have a ticket for this. It could work as well for sstableloader, but there's a requirement for the table/keyspace to exist in the schema already which needs to be checked or handled.

**Comment by Eclion** [comment]
Understood.
Thank you for your answer!
