### ISSUE TITLE
Warning "Can't fetch IAM Role" thrown when using AWS credential file

### ISSUE THREAD

**Issue by baileygm** [thelastpickle/cassandra-medusa#79]
This is a very minor issue but in release 0.5.0 where support for env based S3 authentication has been added a warning is written to the logs each time a file is uploaded if you are using authentication via an AWS credentials file.

Maybe the log level should be set to DEBUG for this message

**Comment by baileygm** [comment]
I'm rerunning some backup tests and finding that a 2GB backup which used to take 2 mins is now taking 30 minutes.  In the logs I can see the message "Can't fetch IAM Role" being repeated hundreds of time per second but no log messages indicating any data being uploaded to S3.

So it appears as first glance that the authentication update has had a large negative impact on performance when using file based credentials.   I'll roll back to the previous medusa version to check whether previous performance is restored and update this issue with my findings.

**Comment by adejanovski** [comment]
I think I may know why.
We should change the priority of authentication methods so that we try to use them in this order:
- credentials file
- env variables
- IAM roles

This is actually the opposite of what we're doing now.

**Comment by baileygm** [comment]
I can confirm that with the previous release the performance is about 20x faster

**Comment by adejanovski** [comment]
thanks @baileygm, 

Could you try with this PR : https://github.com/thelastpickle/cassandra-medusa/pull/80 ?
I've implemented the fix I mentioned above, and just tested all 3 methods successfully.
I'm expecting that you should get the same performance as 0.4.1.

Let me know how it works and I'll cut out a new release.

**Comment by baileygm** [comment]
Yes, I'll give it a try

**Comment by baileygm** [comment]
I ran those tests in our pre-production environment and the backup is now 5 times faster than 0.4.1 using pip3 install https://github.com/thelastpickle/cassandra-medusa/archive/alex/improve-s3-connections.zip.  Quite remarkable !!

**Comment by adejanovski** [comment]
hey, great news ;) 

Thanks for testing this so quickly.

**Comment by adejanovski** [comment]
Fixed in 0.5.1
