### ISSUE TITLE
fqdn parameter from /etc/medusa/medusa.ini is not being read

### ISSUE THREAD

**Issue by thalesac** [thelastpickle/cassandra-medusa#86]
it only works if I set it in the command like i.e.
```
medusa --fqdn hostname backup
```

**Comment by thalesac** [comment]
(google storage)

**Comment by thalesac** [comment]
this is probably due to this default -> https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/medusacli.py#L99

Since it get set to the default, it has precedence over the medusa.ini file.

**Comment by arodrime** [comment]
This was fixed it seems. Closing
