### ISSUE TITLE
restore-cluster command ignore --prefix argument

### ISSUE THREAD

**Issue by liwy00** [thelastpickle/cassandra-medusa#87]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952151)

For two clusters with different "prefix" settings in the medusa.ini, medusa should take the --prefix from command line and overwrite that property in medusa.ini during the restore-cluster process.
Otherwise error will be thrown: backup not found.

Command:
medusa restore-cluster 
    --prefix={the prefix of backup on S3 storage} 
    --backup-name=.....
    .....

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-333) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-333

**Comment by rzvoncek** [comment]
This seems to already work. There is a prefix option for medusa root's cli so running a comand like:
```
medusa --config-file medusa-example.ini --prefix clusterB restore-cluster --backup-name foo
```
Will make the restore-cluster operation happen with `cluserB` regardless of what's configured in the ini file.
