### ISSUE TITLE
Invalid credentials error uploading to s3

### ISSUE THREAD

**Issue by dgpanw** [thelastpickle/cassandra-medusa#96]
I'm exploring the use of medusa, but I'm receiving the following error while attempting to backup a node to s3 using the s3 credentials file. I have tested my credentials via cli and work as expected, so hoping you might be able to share a bit of insight here.

`libcloud.common.types.InvalidCredsError: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>AKIxxxxxxxxxxx</AWSAccessKeyId><StringToSign>AWS4-xxxxxx/us-east-2/s3/aws4_request\n8042b64xxxxxxxxxxx</StringToSign><SignatureProvided>716af78a05b7652420xxxxxxxxxx</SignatureProvided><StringToSignBytes>41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 32 30 32 30 30 33 32 34 54 32 30 32 38 34 38 5a 0a 32 30 32 30 30 33 32 34 2f 75 73 2d 65 61 73 74 2d 32 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 38 30 34 32 62 36 34 36 38 30 63 30 66 65 61 62 39 37 61 36 66 66 30 36 62 39 38 62 61 35 63 32 38 37 64 61 64 39 37 32 64 66 61 37 65 35 65 38 66 63 34 32 36 62 35 65 64 35 63 61 64 37 62 31</StringToSignBytes><CanonicalRequest>PUT\n/medusa-xxxxxxxxxxxxx/messages-5f6776a0478511ea9f06abb9c04a8e65/md-1-big-Digest.crc32\n\naccept-encoding:gzip,deflate\ncontent-type:application/octet-stream\nhost:s3-us-east-2.amazonaws.com,s3-us-east-2.amazonaws.com\nuser-agent:libcloud/2.8.1 (Amazon S3 (us-east-2))\nx-amz-content-sha256:UNSIGNED-PAYLOAD\nx-amz-date:20200324T202848Z\nx-amz-storage-class:STANDARD\n\naccept-encoding;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-storage-class\nUNSIGNED-PAYLOAD</CanonicalRequest><CanonicalRequestBytes>50 55 54 0a 2f 6d 65 64 75 73 61 2d 63 61 73 73 61 6e 64 72 61 2d 62 61 63 6b 75 70 73 2f 70 72 69 73 6d 61 2d 64 6c 70 2d 64 65 76 2f 31 30 2e 31 32 30 2e 31 2e 32 36 2f 64 61 74 61 2f 64 6c 70 5f 70 65 72 66 5f 64 73 73 5f 63 6c 69 65 6e 74 2f 6d 65 73 73 61 67 65 73 2d 35 66 36 37 37 36 61 30 34 37 38 35 31 31 65 61 39 66 30 36 61 62 62 39 63 30 34 61 38 65 36 35 2f 6d 64 2d 31 2d 62 69 67 2d 44 69 67 65 73 74 2e 63 72 63 33 32 0a 0a 61 63 63 65 70 74 2d 65 6e 63 6f 64 69 6e 67 3a 67 7a 69 70 2c 64 65 66 6c 61 74 65 0a 63 6f 6e 74 65 6e 74 2d 74 79 70 65 3a 61 70 70 6c 69 63 61 74 69 6f 6e 2f 6f 63 74 65 74 2d 73 74 72 65 61 6d 0a 68 6f 73 74 3a 73 33 2d 75 73 2d 65 61 73 74 2d 32 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 2c 73 33 2d 75 73 2d 65 61 73 74 2d 32 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 0a 75 73 65 72 2d 61 67 65 6e 74 3a 6c 69 62 63 6c 6f 75 64 2f 32 2e 38 2e 31 20 28 41 6d 61 7a 6f 6e 20 53 33 20 28 75 73 2d 65 61 73 74 2d 32 29 29 0a 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3a 55 4e 53 49 47 4e 45 44 2d 50 41 59 4c 4f 41 44 0a 78 2d 61 6d 7a 2d 64 61 74 65 3a 32 30 32 30 30 33 32 34 54 32 30 32 38 34 38 5a 0a 78 2d 61 6d 7a 2d 73 74 6f 72 61 67 65 2d 63 6c 61 73 73 3a 53 54 41 4e 44 41 52 44 0a 0a 61 63 63 65 70 74 2d 65 6e 63 6f 64 69 6e 67 3b 63 6f 6e 74 65 6e 74 2d 74 79 70 65 3b 68 6f 73 74 3b 75 73 65 72 2d 61 67 65 6e 74 3b 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3b 78 2d 61 6d 7a 2d 64 61 74 65 3b 78 2d 61 6d 7a 2d 73 74 6f 72 61 67 65 2d 63 6c 61 73 73 0a 55 4e 53 49 47 4e 45 44 2d 50 41 59 4c 4f 41 44</CanonicalRequestBytes><RequestId>1DEBF6520BEE42B1</RequestId><HostId>y5c/b8I3mWSYbxxxxxxx=</HostId></Error>'
root@ip-10-120-2-25:/etc/medusa#`

**Comment by adejanovski** [comment]
Hi @dgpanw,

you're sharing a lot of information here, I hope there's nothing too sensitive.
There are two things I could think of:

- Are you connecting to the right region?
- Could you try generating a new set of keys? It seems like some secrets can contain characters that could be improperly escaped (like a `/`).

Let me know if that helps.

**Comment by dgpanw** [comment]
Hi @adejanovski, 

Switching up the aws keys did the trick, much appreciated!
