### ISSUE TITLE
Backup full cluster

### ISSUE THREAD

**Issue by HanumanthPrasad** [thelastpickle/cassandra-medusa#97]
Hi Team,

We have a 4 node cluster and I am trying to take full backup. I am using same backup name and same location to backup full cluster. After 1st node backup is completed successfully, it throws error backup name already exists when trying to take backup on other nodes. 

Do I have to change the backup name or it should be in different location with same name ? If yes, how is it going to work when performing a restore of cluster. 

Also, if I am taking backup with different backup name & location, how should I restore full cluster.

**Comment by adejanovski** [comment]
Hi, @HanumanthPrasad,

the backup name should be the same across nodes, otherwise it's not possible to match each individual backup to a full cluster backup. The location should be the same as well, so that all nodes can see all backups.
Which storage are you using for this backup?
Could you share your medusa.ini file and the command you use to perform the backups?

Thanks

**Comment by HanumanthPrasad** [comment]
Hi,

Please find the attached medusa.ini file and the command used for backup below.
medusa backup --backup-name=test --mode=full

Have changed extension from .ini to .log for attaching. 

[medusa.log](https://github.com/thelastpickle/cassandra-medusa/files/4386316/medusa.log)

Thanks,

**Comment by adejanovski** [comment]
@HanumanthPrasad,

so the `/appshare/cassandrabackup/` is a shared one, and points to a SAN bay or something similar, right?
Could you check what's currently in that folder?

You should have something like this:

```
cassandrabackup
        |
        |---- index
        |            |
        |            |---- backup_index
        |            |
        |            |---- latest_backup
        |
        |---- <hostname1>
        |                  |
        |                  |---- test
        |
        |---- <hostname2>
        |                  |
        |                  |---- test
        |
        |
        |...
```

Do you have something that looks like this?

**Comment by HanumanthPrasad** [comment]
Hi,

I had to run the command on all nodes at the same time and backup worked. But I am now facing an issue with restore. 

I am trying to restore entire 4 node cluster in 1 new node configured in different DC and rack. It throws me below error. I have added ssh username and key file but issue remains the same.

ERROR: Failed to run on host <HOSTNAME>
ERROR: This error happened during the cluster restore: ('Authentication error while connecting to %s:%s.', '<HOSTNAME>', '22')
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/pssh/clients/miko/single.py", line 199, in _connect
    **paramiko_kwargs)
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 740, in _auth
    self._transport.auth_publickey(username, key)
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1580, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/local/lib/python3.6/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed. 

Can you please advise.

**Comment by adejanovski** [comment]
I'll close this ticket as the backup succeeded, could you please create a new issue for that authentication problem?
Thanks!
