### ISSUE TITLE
Is there any possibility for Cluster performence impact

### ISSUE THREAD

**Issue by Pradeep2get** [thelastpickle/cassandra-medusa#98]
Hi Team,
I have a cluster with 3 nodes and scheduled a differential backup for every 15 mins. I am facing a cluster performance issue. I want to know is this a correct option to have 15 mins backup schedule. 
Cluster Details
Cassandra Version 3.11.5
2vCPU/16GB - 3 Nodes
SSD Disk for Data and Backup
Any Suggestions

**Comment by adejanovski** [comment]
Hi @Pradeep2get,

first of all, running Cassandra on 2 vCPU is not recommended for production use. We usually recommend 8 vCPUs at least for production and 4 vCPUs for test/staging environments.

Medusa will use disk and network mostly and the consumption will largely depend on how much data needs to be uploaded for each backup.
If you perform backups every 15 minutes without defining a purge policy, you may also end up with a LOT of backups there, which involve overhead in some operations that Medusa performs (like listing the backups for example).

Did you try pausing the backups to see if it's really what's impacting your cluster?
What metrics are currently affected ? read or write latencies?
Are backups running when you're seeing performance issues? Are you observing that the network or the disks are overwhelmed?

**Comment by Pradeep2get** [comment]
@adejanovski Thanks for your response. 
Yes, we have a retention policy for the last 100 backups local. 
Yes, We are facing issues in **disk write** latencies. We monitored the data write latencies during the backup using the **DSTAT**.
But in our environment, not that much requests and record size will come but we are facing an issue.
Now I am also thinking the VM size may be an issue.

**Comment by adejanovski** [comment]
@Pradeep2get,

are you still experiencing this issue? Did you move to larger VMs?

**Comment by Pradeep2get** [comment]
@adejanovski Thanks

We increased the VM size, now we are not facing this issue frequently.
